import test from "node:test";import assert from "node:assert/strict";
import {routeIncoming} from "../src/webhook.js";import {memoryStore} from "../src/store.js";
// Tom (23.9): phone numbers pass only after BOTH sides were shown the match and each confirmed it's relevant.
const now=new Date("2026-09-23T08:00:00+03:00");
const available=async i=>({kind:"availability",date:i.date,slots:[{courtId:"c3",courtName:"3",start:"19:00",end:"20:30",durationMinutes:i.durationMinutes,price:null}]});
const A="972501111111",B="972502222222",PHONE=/05\d-\d{7}|wa\.me\/\d/;
const say=(s,u,o)=>routeIncoming({userId:u,displayName:"x",store:s,now,availabilityFn:available,...o});
// ctaUrl urls count too: a wa.me link carries the number.
const texts=r=>[r.text||"",r.ctaUrl?.url||"",...(r.notifications||[]).flatMap(n=>[n.response.text||"",n.response.ctaUrl?.url||""])];
async function register(s,u,name){await say(s,u,{actionId:"oneoff"});for(const o of [{actionId:"level:3–3.5"},{text:"מחר אחרי 19:00"},{actionId:"duration:90"},{actionId:"party:1"},])await say(s,u,o);const ask=await say(s,u,{actionId:"court:yes"});assert.match(ask.text,/^(באיזה שם להציג אתכם|להופיע בלוח המשחקים בתור)/);return say(s,u,{text:name});}
async function matched(){const s=memoryStore(),seen=[];seen.push(...texts(await register(s,A,"יוסי")));const r=await register(s,B,"דנה");seen.push(...texts(r));const toA=r.notifications.find(n=>n.to===A);assert(toA,"A is approached with the match");assert.match(toA.response.text,/מצאתי התאמה אפשרית/);const connect=toA.response.buttons.find(b=>b.id.startsWith("connect:"));return{s,seen,connect};}
test("finding a match reveals no phone number to either side",async()=>{const {seen}=await matched();for(const t of seen)assert.doesNotMatch(t,PHONE,t);});
test("one side approves, other still pending -> no numbers",async()=>{const {s,connect}=await matched();const r=await say(s,A,{actionId:connect.id});for(const t of texts(r))assert.doesNotMatch(t,PHONE,t);const toB=r.notifications.find(n=>n.to===B);assert(toB,"B is asked to confirm");assert(toB.response.buttons.some(b=>b.id.startsWith("accept:")));});
test("one side approves, other declines -> no numbers to anyone",async()=>{const {s,connect}=await matched();const r=await say(s,A,{actionId:connect.id});const acc=r.notifications.find(n=>n.to===B).response.buttons.find(b=>b.id.startsWith("decline:"));const d=await say(s,B,{actionId:acc.id});for(const t of texts(d))assert.doesNotMatch(t,PHONE,t);});
test("both approve -> each side gets a שלח הודעה button to the other",async()=>{const {s,connect}=await matched();const r=await say(s,A,{actionId:connect.id});const acc=r.notifications.find(n=>n.to===B).response.buttons.find(b=>b.id.startsWith("accept:"));const ok=await say(s,B,{actionId:acc.id});// Tom 23.9 15:01: a "שלח הודעה" button (wa.me) instead of the number in the text.
assert.doesNotMatch(ok.text,/05\d-\d{7}/);assert.deepEqual(ok.ctaUrl,{displayText:"שלח הודעה",url:"https://wa.me/972501111111"});const toA=ok.notifications.find(n=>n.to===A);assert.doesNotMatch(toA.response.text,/05\d-\d{7}/);assert.deepEqual(toA.response.ctaUrl,{displayText:"שלח הודעה",url:"https://wa.me/972502222222"});});
test("a second accept tap or a stranger's accept cannot leak numbers",async()=>{const {s,connect}=await matched();const r=await say(s,A,{actionId:connect.id});const acc=r.notifications.find(n=>n.to===B).response.buttons.find(b=>b.id.startsWith("accept:"));const stranger=await say(s,"972503333333",{actionId:acc.id});for(const t of texts(stranger))assert.doesNotMatch(t,PHONE,t);const self=await say(s,A,{actionId:acc.id});for(const t of texts(self))assert.doesNotMatch(t,PHONE,t);});
