import test from "node:test";import assert from "node:assert/strict";import {parseIntentLocal} from "../src/intent.js";import {handleConversation} from "../src/conversation.js";import {memoryStore} from "../src/store.js";
// Tom 23.9 10:46 hour rules: 1-7 evening unless stated; 8/9/10 ask; 11/12 midday. His examples: "שעה שש" and "ב6" = 18:00.
const now=new Date("2026-09-23T10:36:00+03:00"),st=t=>parseIntentLocal(t,now).startMinute;
test("Tom's examples: שעה שש and ב6 are 18:00",()=>{assert.equal(st("מחר שעה שש"),1080);assert.equal(st("מחר ב6"),1080);});
test("1-7 default to evening, morning cue keeps AM",()=>{assert.equal(st("מחר ב1"),780);assert.equal(st("מחר בשבע"),1140);assert.equal(st("מחר ב7 בבוקר"),420);});
test("11 and 12 are midday",()=>{assert.equal(st("מחר ב11"),660);assert.equal(st("מחר ב12"),720);assert.equal(st("מחר באחת עשרה"),660);});
for(const t of ["מחר ב8","מחר ב-9","מחר בעשר","מחר אחרי 9"])test(`"${t}" is ambiguous`,()=>assert(parseIntentLocal(t,now).ambiguousHour));
test("8-10 with a cue are not ambiguous",()=>{assert.equal(parseIntentLocal("מחר ב-9 בבוקר",now).ambiguousHour,undefined);assert.equal(st("מחר ב-9 בערב"),1260);assert.equal(st("מחר ב-20:00"),1200);});
test("bot asks morning or evening for 8-10, then continues with the pick",async()=>{const s=memoryStore();await handleConversation({userId:"a",actionId:"availability",store:s,now});const q=await handleConversation({userId:"a",text:"מחר ב-9",store:s,now});assert.equal(q.text,"התכוונת ל-9 בבוקר או ל-9 בערב?");assert.deepEqual(q.buttons.map(b=>[b.id,b.title]),[["ampm:am","9 בבוקר"],["ampm:pm","9 בערב"]]);const r=await handleConversation({userId:"a",actionId:"ampm:pm",store:s,now});assert.equal(r.mode,"availability");assert.equal(parseIntentLocal(r.query,now).startMinute,1260);});
test("players flow: ambiguous hour asks, pick continues to duration",async()=>{const s=memoryStore();for(const a of ["players","oneoff","level:3"])await handleConversation({userId:"b",actionId:a,store:s,now});const q=await handleConversation({userId:"b",text:"מחר ב10",store:s,now});assert.match(q.text,/10 בבוקר או ל-10 בערב/);const r=await handleConversation({userId:"b",actionId:"ampm:am",store:s,now});assert.match(r.text,/כמה זמן/);assert.equal((await s.get("state/b")).draft.startMinute,600);});
