import test from "node:test";import assert from "node:assert/strict";
import {routeIncoming} from "../src/webhook.js";import {memoryStore} from "../src/store.js";import {messageInput} from "../netlify/functions/whatsapp.js";import {PLAYERS_MENU} from "../src/conversation.js";
import {makeUser,turnAll} from "./harness.mjs";
// Live 23.9 10:23-10:26: taps on "מגרש פנוי" and the name answer looked dead. Router ran and Meta accepted,
// but the replies were interactive LISTS with non-ASCII row ids ("when:היום בערב", "level:1–2") that never reached the phone.
const now=new Date("2026-09-23T10:23:00+03:00");
const available=async i=>({kind:"availability",date:i.date,slots:[{courtId:"c3",courtName:"3",start:"19:00",end:"20:30",durationMinutes:90,price:200}]});
// Real Meta payload shapes (as received by the webhook)
const buttonTap=(id,title)=>({from:"972544819860",id:"wamid.X",type:"interactive",interactive:{type:"button_reply",button_reply:{id,title}}});
const listTap=(id,title)=>({from:"972544819860",id:"wamid.Y",type:"interactive",interactive:{type:"list_reply",list_reply:{id,title}}});
const textMsg=body=>({from:"972544819860",id:"wamid.Z",type:"text",text:{body}});
const say=(s,msg)=>routeIncoming({userId:"972544819860",displayName:"Tom Keidar",store:s,now,availabilityFn:available,...messageInput(msg)});
const allIds=r=>[...(r.buttons||[]).map(b=>b.id),...(r.list?r.list.sections.flatMap(x=>x.rows.map(y=>y.id)):[])];
const ascii=id=>/^[\x20-\x7e]+$/.test(id);
test("real payloads: menu -> 'מגרש פנוי' tap -> when list with ASCII ids -> list tap -> availability",async()=>{const s=memoryStore();await say(s,textMsg("שלום"));const q=await say(s,buttonTap("availability","מגרש פנוי"));assert.match(q.text,/מתי תרצו לשחק/);assert(q.list);for(const id of allIds(q))assert(ascii(id),id);const row=q.list.sections[0].rows.find(r=>r.title==="מחר בערב");const r=await say(s,listTap(row.id,row.title));assert.match(r.text,/זמינות|19:00|אין מגרש פנוי/);});
test("real payloads: recurring flow asks flow questions first, name only before publishing, typed name is captured",async()=>{const s=memoryStore();await say(s,buttonTap("players","מציאת שחקנים"));const lv=await say(s,buttonTap("recurring","משחק קבוע כל שבוע"));assert.equal(lv.text,"מה הרמה שלכם?");const row=lv.list.sections[0].rows[3];assert(ascii(row.id));const w=await say(s,listTap(row.id,row.title));assert.match(w.text,/באילו ימים ושעות/);const d=await say(s,textMsg("שני ורביעי אחרי 20:00"));const d2=await say(s,listTap(d.list.sections[0].rows[1].id,""));const p=await say(s,listTap(d2.list.sections[0].rows[0].id,""));const c=await say(s,buttonTap("court:yes","כן"));const ask=await say(s,listTap(c.list.sections[0].rows[0].id,""));assert.match(ask.text,/^מה השם שלך\?/);const done=await say(s,textMsg("תום"));assert.match(done.text,/הבקשה נשמרה/);assert.equal((await s.get("profile/972544819860")).name,"תום");const req=(await s.list("request/"))[0].value;assert.equal(req.displayName,"תום");assert.equal(req.level,"3–3.5");});
test("every list row id and button id the bot sends is ASCII (whole 100-conversation style walk)",async()=>{const u=makeUser("972500009999","דנה");const steps=[{text:"שלום"},{actionId:"availability"},{actionId:"players"},{actionId:"board"},{actionId:"menu"},{actionId:"players"},{actionId:"oneoff"},{actionId:"level:3"},{text:"מחר אחרי 19:00"},{actionId:"duration:90"},{actionId:"party:1"},{actionId:"court:yes"},{actionId:"flex:0"},{actionId:"settings"},{actionId:"mute_custom"}];for(const st of steps){for(const t of await turnAll(u,st))for(const o of t.outbound){const i=o.interactive;if(!i)continue;const ids=[...(i.action?.buttons||[]).map(b=>b.reply.id),...(i.action?.sections||[]).flatMap(x=>x.rows.map(r=>r.id))];for(const id of ids){assert(ascii(id),`${JSON.stringify(st)} -> ${id}`);assert(id.length<=200);}}}});
test("board: 'להצטרף למשחק חד-פעמי' asks מתי first, then searches that window, then shows results or the empty state",async()=>{const s=memoryStore();const q=await say(s,buttonTap("board","להצטרף למשחק חד-פעמי"));assert.match(q.text,/מתי תרצו לשחק/);assert.doesNotMatch(q.text,/לא מצאתי/);assert(q.list);for(const id of allIds(q))assert(ascii(id),id);const row=q.list.sections[0].rows.find(r=>r.title==="מחר בערב");const r=await say(s,listTap(row.id,row.title));assert.match(r.text,/לא מצאתי|בקשות/);const q2=await say(s,buttonTap("board",""));const r2=await say(s,textMsg("מחר אחרי 19:00"));assert.match(r2.text,/לא מצאתי|בקשות/);});
test("no message carries both the 'כתבו תפריט' line and a menu button/row",async()=>{const u=makeUser("972500008888","רון");for(const st of [{text:"שלום"},{text:"בננה"},{text:"מה?"},{actionId:"players"},{actionId:"board"},{text:"מחר בערב"},{actionId:"oneoff"},{actionId:"availability"},{text:"מחר בערב"}]){for(const t of await turnAll(u,st))for(const o of t.outbound){const body=o.text?.body||o.interactive?.body?.text||"";const hasMenu=JSON.stringify(o).includes('"id":"menu"');assert(!(hasMenu&&/כתבו \*?תפריט/.test(body)),body);}}});
test("players menu text is exactly Tom's approved copy with emoji, same three buttons",async()=>{const s=memoryStore();const r=await say(s,buttonTap("players","מציאת שחקנים"));assert.equal(r.text,"מה בא לכם?\n\n👥 חסרים לי שחקנים - יש לכם מגרש וזמן, וחסרים שחקנים להשלמת רביעייה.\n\n⚡ להצטרף למשחק חד-פעמי - רוצים לראות משחקים פתוחים ולהצטרף.\n\n🔁 משחק קבוע כל שבוע - רושמים פעם אחת את הזמנים שנוחים, וכל שבוע המערכת תנסה לשדך לכם שחקנים. בלי התחייבות - אפשר לעדכן או להסיר בכל רגע.");assert.equal(r.text,PLAYERS_MENU);assert.deepEqual(r.buttons.map(b=>b.id),["oneoff","board","recurring"]);});
