import test from "node:test";import assert from "node:assert/strict";
import {handleConversation} from "../src/conversation.js";import {dailySweep,publicBoard} from "../src/matching.js";import {memoryStore} from "../src/store.js";
const now=new Date("2026-09-23T08:00:00+03:00");
const available=async i=>({kind:"availability",date:i.date,slots:[{courtId:"c3",courtName:"3",start:"19:00",end:"20:30",durationMinutes:i.durationMinutes,price:225}]});
async function flow(store,userId,name,{recurring=false,level="3–3.5",when="מחר אחרי 19:00",duration=90,party=1,court=false,flex=30}={}){await handleConversation({userId,displayName:name,actionId:recurring?"recurring":"oneoff",store,now,availabilityFn:available});await handleConversation({userId,displayName:name,actionId:`level:${level}`,store,now,availabilityFn:available});await handleConversation({userId,displayName:name,text:when,store,now,availabilityFn:available});await handleConversation({userId,displayName:name,actionId:`duration:${duration}`,store,now,availabilityFn:available});await handleConversation({userId,displayName:name,actionId:`party:${party}`,store,now,availabilityFn:available});await handleConversation({userId,displayName:name,actionId:`court:${court?"yes":"no"}`,store,now,availabilityFn:available});return handleConversation({userId,displayName:name,actionId:`flex:${flex}`,store,now,availabilityFn:available});}
test("interactive intake stores public request and produces on-request match",async()=>{const s=memoryStore();await flow(s,"u1","דנה",{});const r=await flow(s,"u2","נועם",{});assert.match(r.text,/מצאתי 1 התאמות/);assert.equal(r.notifications.length,1);const board=await publicBoard(s,{date:"2026-09-24",startMinute:1140,endMinute:1380,now});assert.equal(board.length,2);assert(board.every(x=>!JSON.stringify(x).match(/05\d{8}/)));});
test("recurring availability participates in daily sweep and respects mute",async()=>{const s=memoryStore();await flow(s,"u1","דנה",{recurring:true,when:"ימי חמישי אחרי 19:00"});await flow(s,"u2","נועם",{recurring:true,when:"ימי חמישי אחרי 19:00"});const first=await dailySweep(s,now);assert(first.length>=1);const again=await dailySweep(s,now);assert.equal(again.length,0);await handleConversation({userId:"u1",actionId:"mute_week",store:s,now,availabilityFn:available});await flow(s,"u3","מיכל",{recurring:true,when:"ימי חמישי אחרי 19:00"});const muted=await dailySweep(s,new Date("2026-09-23T09:00:00+03:00"));assert(muted.every(pair=>pair.every(x=>x.userId!=="u1")));});
test("welcome and closed choices are native interactive payloads",async()=>{const s=memoryStore(),w=await handleConversation({userId:"u",text:"שלום",store:s,now,availabilityFn:available});assert.equal(w.buttons.length,2);const p=await handleConversation({userId:"u",actionId:"players",store:s,now,availabilityFn:available});assert.equal(p.buttons.length,3);const l=await handleConversation({userId:"u",actionId:"oneoff",store:s,now,availabilityFn:available});assert(l.list.sections[0].rows.length>=5);});
test("custom mute and settings menu work",async()=>{const s=memoryStore();const menu=await handleConversation({userId:"u",text:"הגדרות",store:s,now,availabilityFn:available});assert.equal(menu.buttons.length,3);await handleConversation({userId:"u",actionId:"mute_14",store:s,now,availabilityFn:available});const p=await s.get("profile/u");assert(new Date(p.mutedUntil)>now);});

test("one-off request is not published when no live court fits",async()=>{const s=memoryStore(),none=async i=>({kind:"availability",date:i.date,slots:[]});await handleConversation({userId:"x",actionId:"oneoff",store:s,now,availabilityFn:none});await handleConversation({userId:"x",actionId:"level:3–3.5",store:s,now,availabilityFn:none});await handleConversation({userId:"x",text:"מחר אחרי 19:00",store:s,now,availabilityFn:none});await handleConversation({userId:"x",actionId:"duration:90",store:s,now,availabilityFn:none});await handleConversation({userId:"x",actionId:"party:1",store:s,now,availabilityFn:none});await handleConversation({userId:"x",actionId:"court:no",store:s,now,availabilityFn:none});const r=await handleConversation({userId:"x",actionId:"flex:30",store:s,now,availabilityFn:none});assert.match(r.text,/לא מצאתי מגרש פנוי/);assert.equal((await s.list("request/")).length,0);});
