import test from "node:test";import assert from "node:assert/strict";
import {handleConversation} from "../src/conversation.js";import {dailySweep,publicBoard} from "../src/matching.js";import {memoryStore,named} from "./named-store.mjs";
const now=new Date("2026-09-23T08:00:00+03:00");
const available=async i=>({kind:"availability",date:i.date,slots:[{courtId:"c3",courtName:"3",start:"19:00",end:"20:30",durationMinutes:i.durationMinutes,price:null}]});
async function flow(store,userId,name,{recurring=false,level="3–3.5",when="מחר אחרי 19:00",duration=90,party=1,court=false,flex=60}={}){await named(store,userId,name);await handleConversation({userId,displayName:name,actionId:recurring?"recurring":"oneoff",store,now,availabilityFn:available});await handleConversation({userId,displayName:name,actionId:`level:${level}`,store,now,availabilityFn:available});await handleConversation({userId,displayName:name,text:when,store,now,availabilityFn:available});await handleConversation({userId,displayName:name,actionId:`duration:${duration}`,store,now,availabilityFn:available});await handleConversation({userId,displayName:name,actionId:`party:${party}`,store,now,availabilityFn:available});await handleConversation({userId,displayName:name,actionId:`court:${court?"yes":"no"}`,store,now,availabilityFn:available});const r=await handleConversation({userId,displayName:name,actionId:`flex:${flex}`,store,now,availabilityFn:available});return r.buttons?.some(b=>b.id==='court_consent:yes')?handleConversation({userId,displayName:name,actionId:'court_consent:no',store,now,availabilityFn:available}):r;}
test("interactive intake stores public request and produces on-request match",async()=>{const s=memoryStore();await flow(s,"u1","דנה",{});const r=await flow(s,"u2","נועם",{});assert.match(r.text,/מצאתי התאמה אפשרית ושלחתי הצעה/);assert.equal(r.notifications.length,1);const board=await publicBoard(s,{date:"2026-09-24",startMinute:1140,endMinute:1380,now});assert.equal(board.length,2);assert(board.every(x=>!JSON.stringify(x).match(/05\d{8}/)));});
test("recurring availability participates in daily sweep; a user who left the list is out of it (Tom 14:13)",async()=>{const s=memoryStore();await flow(s,"u1","דנה",{recurring:true,when:"ימי חמישי אחרי 19:00"});await flow(s,"u2","נועם",{recurring:true,when:"ימי חמישי אחרי 19:00"});const first=await dailySweep(s,now);assert.equal(first.length,0);/* offered instantly on registration; Tom 23.9 15:36: never re-offered */const again=await dailySweep(s,now);assert.equal(again.length,0);await handleConversation({userId:"u1",actionId:"leave_yes",store:s,now,availabilityFn:available});await flow(s,"u3","מיכל",{recurring:true,when:"ימי חמישי אחרי 19:00"});const muted=await dailySweep(s,new Date("2026-09-23T09:00:00+03:00"));assert(muted.every(pair=>pair.every(x=>x.userId!=="u1")));});
test("welcome and closed choices are native interactive payloads",async()=>{const s=memoryStore(),w=await handleConversation({userId:"u",text:"שלום",store:s,now,availabilityFn:available});assert.deepEqual(w.buttons.map(b=>b.id),["availability","players","club"]);const p=await handleConversation({userId:"u",actionId:"players",store:s,now,availabilityFn:available});assert.equal(p.buttons.length,3);const l=await handleConversation({userId:"u",actionId:"oneoff",store:s,now,availabilityFn:available});assert(l.list.sections[0].rows.length>=5);});
test("settings menu: my requests + leave the list, no mute (Tom 14:13); stale mute taps point to leave",async()=>{const s=memoryStore();const menu=await handleConversation({userId:"u",text:"הגדרות",store:s,now,availabilityFn:available});assert.deepEqual(menu.buttons.map(b=>b.id),["my_requests","leave"]);const old=await handleConversation({userId:"u",actionId:"mute_14",store:s,now,availabilityFn:available});assert.ok(old.buttons.some(b=>b.id==="leave"));const p=await s.get("profile/u");assert(!p?.mutedUntil);});

test("one-off no-court request can be saved when no court fits, with a separate alert choice",async()=>{const s=memoryStore(),none=async i=>({kind:"availability",date:i.date,slots:[]});const h=o=>handleConversation({userId:"x",store:s,now,availabilityFn:none,...o});await h({actionId:"oneoff"});await h({actionId:"level:3–3.5"});await h({text:"מחר אחרי 19:00"});await h({actionId:"party:1"});await h({actionId:"court:no"});const prompt=await h({actionId:"flex:60"});assert.match(prompt.text,/התראה אחת/);assert.equal((await s.list("request/")).length,0);const result=await h({actionId:"court_consent:no"});assert.match(result.text,/הבקשה נשמרה/);assert.equal((await s.list("request/")).length,1);});
test("public board shows an open-ended window as אחרי HH:MM, never 00:00 or 24:00 (QA 23.9)",async()=>{const s=memoryStore();await flow(s,"u1","דנה",{});const board=await handleConversation({userId:"viewer",displayName:"נועם",text:"מי מחפש משחק מחר בערב?",store:s,now,availabilityFn:available});assert.match(board.text,/אחרי 19:00/);assert.doesNotMatch(board.text,/24:00|–00:00/);});
