import test from "node:test";import assert from "node:assert/strict";
import {routeIncoming} from "../src/webhook.js";import {memoryStore} from "../src/store.js";import {nextWeekDays,handleConversation} from "../src/conversation.js";import {parseIntentLocal} from "../src/intent.js";
// Live 23.9 10:36: Tom typed "בשבוע הבא אחרי 18:00" and got "לא הבנתי".
const now=new Date("2026-09-23T10:36:00+03:00"),T="בשבוע הבא אחרי 18:00";
let asked=[];const av=async i=>{asked.push(i);return{kind:"availability",date:i.date,slots:[{courtId:"c3",courtName:"3",start:"19:00",end:"20:30",durationMinutes:90,price:200}]};};
const say=(s,o)=>routeIncoming({userId:"972544819860",displayName:"Tom",store:s,now,availabilityFn:av,...o});
test("next week = next Sunday..Saturday in Israel",()=>{const d=nextWeekDays(now);assert.equal(d[0].date,"2026-09-27");assert.equal(d[0].label,"ראשון 27.9");assert.equal(d[6].date,"2026-10-03");});
for(const pre of [[{text:"שלום"},{actionId:"menu"}],[{actionId:"availability"}]])test(`"${T}" after ${pre.map(p=>p.actionId||p.text).join(",")} asks which day next week, then checks that day after 18:00`,async()=>{const s=memoryStore();for(const p of pre)await say(s,p);const q=await say(s,{text:T});assert.doesNotMatch(q.text,/לא הבנתי/);assert.equal(q.text,"באיזה יום בשבוע הבא?");const rows=q.list.sections[0].rows;assert.equal(rows[1].title,"שני 28.9");assert(rows.every(r=>/^[\x20-\x7e]+$/.test(r.id)));const r=await handleConversation({userId:"972544819860",displayName:"Tom",store:s,now,availabilityFn:av,actionId:rows[1].id});assert.equal(r.mode,"availability");const p=parseIntentLocal(r.query,now);assert.equal(p.date,"2026-09-28");assert.equal(p.startMinute,1080);});
test(`"${T}" on the board's when question searches the picked day`,async()=>{const s=memoryStore();await say(s,{actionId:"board"});const q=await say(s,{text:T});assert.equal(q.text,"באיזה יום בשבוע הבא?");const r=await say(s,{actionId:q.list.sections[0].rows[2].id});assert.match(r.text,/לא מצאתי|בקשות|אין כרגע משחקים פתוחים/);});
test(`"${T}" in the one-off players flow continues to duration with the picked day`,async()=>{const s=memoryStore();for(const a of ["players","oneoff","level:3"])await say(s,{actionId:a});const q=await say(s,{text:T});assert.equal(q.text,"באיזה יום בשבוע הבא?");const r=await say(s,{actionId:q.list.sections[0].rows[0].id});assert.match(r.text,/כמה אתם/);const st=await s.get("state/972544819860");assert.equal(st.draft.date,"2026-09-27");assert.equal(st.draft.startMinute,1080);});
