import test from "node:test";import assert from "node:assert/strict";
import {handleConversation} from "../src/conversation.js";import {memoryStore,named} from "./named-store.mjs";
const now=new Date("2026-09-23T08:00:00+03:00");
const available=async i=>({kind:"availability",date:i.date,slots:[{courtId:"c3",courtName:"3",start:"19:00",end:"20:30",durationMinutes:i.durationMinutes,price:null}]});
async function upTo(store,userId){const h=o=>handleConversation({userId,displayName:"דנה",store,now,availabilityFn:available,...o});await h({actionId:"oneoff"});return{h,party:await h({actionId:"level:3–3.5"})};}
// Critique 23.9 item 9: party and court in one question, Tom's party labels kept.
test("party+court question uses Tom's party labels, mapped to 1/2/3 and yes/no",async()=>{const {party}=await upTo(memoryStore(),"a");assert.equal(party.text,"כמה אתם, והאם כבר יש לכם מגרש?");const rows=party.list.sections.flatMap(x=>x.rows).filter(r=>r.id.startsWith("pc:"));assert.deepEqual(rows.map(r=>[r.id,r.title]),[["pc:1:yes","רק אני · יש מגרש"],["pc:1:no","רק אני · בלי מגרש"],["pc:2:yes","אני ועוד אחד · יש מגרש"],["pc:2:no","אני ועוד אחד · בלי מגרש"],["pc:3:yes","שלושה · יש מגרש"],["pc:3:no","שלושה · בלי מגרש"]]);assert.equal(rows[4].description,"מחפשים רביעי");for(const r of rows)assert(r.title.length<=24);});
for(const [n,label] of [[1,"רק אני"],[2,"אני ועוד אחד"],[3,"שלושה, מחפשים רביעי"]])test(`"${label}" stores partySize ${n}`,async()=>{const s=memoryStore(),{h}=await upTo(s,"u"+n);await h({actionId:`pc:${n}:yes`});await h({text:"מחר אחרי 19:00"});await h({actionId:"duration:90"});const reqs=(await s.list("request/")).map(x=>x.value);assert.equal(reqs.length,1);assert.equal(reqs[0].partySize,n);});
test("old party prompt is gone",async()=>{const src=(await import("node:fs")).readFileSync(new URL("../src/conversation.js",import.meta.url),"utf8");assert(!src.includes("כמה שחקנים כבר יש בבקשה"));});
