import test from "node:test";import assert from "node:assert/strict";
import {routeIncoming} from "../src/webhook.js";import {memoryStore} from "../src/store.js";
const now=new Date("2026-09-23T08:00:00+03:00");
const available=async i=>({kind:"availability",date:i.date,slots:[{courtId:"c3",courtName:"3",start:"19:00",end:"20:30",durationMinutes:i.durationMinutes,price:null}]});
const PHONE="972501234567";
const say=(store,o,userId=PHONE)=>routeIncoming({userId,displayName:"Tom Keidar",store,now,availabilityFn:available,...o});
async function register(store,userId=PHONE){for(const o of [{actionId:"level:3–3.5"},{text:"מחר אחרי 19:00"},{actionId:"duration:90"},{actionId:"party:1"},])await say(store,o,userId);return say(store,{actionId:"court:yes"},userId);}
const setName=(s,n,u=PHONE)=>s.set(`profile/${u}`,{userId:u,name:n});
const nameOf=async(s,u=PHONE)=>(await s.get(`profile/${u}`))?.name||null;

// Tom 23.9: flow questions first; the name is asked only right before publishing (or connecting).
test("player flow asks level/when first; the name is asked right before publishing, saved per number, and the request is published",async()=>{const s=memoryStore();const q=await say(s,{actionId:"oneoff"});assert.equal(q.text,"מה הרמה שלכם?");assert.doesNotMatch(q.text,/השם/);const ask=await register(s);assert.match(ask.text,/^מה השם שלך\?/);assert.equal((await s.list("request/")).length,0);const r=await say(s,{text:"יוסי"});assert.equal(await nameOf(s),"יוסי");assert.equal(r.text,"הבקשה נשמרה ותופיע בלוח המשחקים.\n\nאעדכן כשאמצא התאמה.");const req=(await s.list("request/"))[0].value;assert.equal(req.displayName,"יוסי");});
test("recurring flow asks level then מתי before any name question",async()=>{const s=memoryStore();const a=await say(s,{actionId:"recurring"});assert.equal(a.text,"מה הרמה שלכם?");const b=await say(s,{actionId:"level:3"});assert.match(b.text,/באילו ימים ושעות/);});
test("WhatsApp profile name is not used silently as the player name",async()=>{const s=memoryStore();await say(s,{actionId:"oneoff"});assert.equal(await nameOf(s),null);});
test("a question typed at the name step is not saved as a name",async()=>{const s=memoryStore();await say(s,{actionId:"oneoff"});await register(s);const r=await say(s,{text:"מה פנוי מחר?"});assert.match(r.text,/לא הצלחתי לקלוט שם/);assert.equal(await nameOf(s),null);});
test("menu escapes the name step",async()=>{const s=memoryStore();await say(s,{actionId:"oneoff"});await register(s);const r=await say(s,{text:"תפריט"});assert.match(r.text,/ברוכים הבאים/);});
test("returning user is greeted by name and not asked again",async()=>{const s=memoryStore();await setName(s,"יוסי");const w=await say(s,{text:"שלום"});assert.match(w.text,/^\*שלום יוסי, ברוכים הבאים ל־GT PADEL\*/);const again=await say(s,{actionId:"recurring"});assert.equal(again.text,"מה הרמה שלכם?");});
test("request-saved text is exactly Tom's copy, no phone-privacy line",async()=>{const s=memoryStore();await setName(s,"יוסי");await say(s,{actionId:"oneoff"});const r=await register(s);assert.equal(r.text,"הבקשה נשמרה ותופיע בלוח המשחקים.\n\nאעדכן כשאמצא התאמה.");assert.doesNotMatch(r.text,/טלפון/);});
test("public board shows the player's name and WhatsApp phone number",async()=>{const s=memoryStore();await setName(s,"יוסי");await say(s,{actionId:"oneoff"});await register(s);const b=await say(s,{text:"מי מחפש משחק מחר בערב?"},"972529999999");assert.match(b.text,/יוסי · 050-1234567 · רמה 3–3\.5/);const rows=b.list.sections.flatMap(x=>x.rows).filter(x=>x.id.startsWith("connect:"));assert.match(rows[0].description,/^050-1234567 · /);});
for(const phrase of ["אני רוצה לשנות את השם","השם שלי הוא לא יוסי"])test(`"${phrase}" asks for the new name, then confirms old -> new before saving`,async()=>{const s=memoryStore();await setName(s,"יוסי");const q=await say(s,{text:phrase});assert.match(q.text,/מה השם שלך\?/);const c=await say(s,{text:"אבי"});assert.equal(c.text,"לאשר שינוי שם מ-יוסי ל-אבי?");assert.deepEqual(c.buttons.slice(0,2).map(b=>b.id),["name_yes","name_no"]);assert.equal(await nameOf(s),"יוסי");const ok=await say(s,{actionId:"name_yes"});assert.match(ok.text,/השם עודכן ל-אבי/);assert.equal(await nameOf(s),"אבי");});
test(`"קוראים לי אבי" captures the name and goes straight to confirmation`,async()=>{const s=memoryStore();await setName(s,"יוסי");const c=await say(s,{text:"קוראים לי אבי"});assert.equal(c.text,"לאשר שינוי שם מ-יוסי ל-אבי?");assert.equal(await nameOf(s),"יוסי");await say(s,{actionId:"name_yes"});assert.equal(await nameOf(s),"אבי");});
test("declining the change keeps the old name",async()=>{const s=memoryStore();await setName(s,"יוסי");await say(s,{text:"קוראים לי אבי"});const r=await say(s,{actionId:"name_no"});assert.match(r.text,/השם נשאר יוסי/);assert.equal(await nameOf(s),"יוסי");});
test("confirmed name change updates the name on the user's active board requests",async()=>{const s=memoryStore();await setName(s,"יוסי");await say(s,{actionId:"oneoff"});await register(s);await say(s,{text:"קוראים לי אבי"});await say(s,{actionId:"name_yes"});const b=await say(s,{text:"מי מחפש משחק מחר בערב?"},"972529999999");assert.match(b.text,/אבי · 050-1234567/);assert.doesNotMatch(b.text,/יוסי/);});
test("names are keyed per WhatsApp number",async()=>{const s=memoryStore();await setName(s,"יוסי");await say(s,{actionId:"oneoff"},"972527777777");const other=await register(s,"972527777777");assert.match(other.text,/^מה השם שלך\?/);assert.equal(await nameOf(s),"יוסי");});
test("connection flow: no stale privacy claims; on accept both sides get the other's phone",async()=>{const s=memoryStore();await setName(s,"יוסי");await say(s,{actionId:"oneoff"});await register(s);const req=(await s.list("request/"))[0].value;const V="972528888888";await say(s,{actionId:`connect:${req.id}`},V);const sent=await say(s,{text:"דנה"},V);assert.match(sent.text,/^שלחתי בקשת חיבור ליוסי\./);assert.doesNotMatch(sent.text,/חסוי/);const c=(await s.list("connection/"))[0].value;assert.equal(c.fromDisplayName,"דנה");const acc=await say(s,{actionId:`accept:${c.id}`});assert.match(acc.text,/דנה: 052-8888888/);assert.match(acc.notifications[0].response.text,/החיבור עם יוסי אושר! אפשר ליצור קשר: 050-1234567/);for(const t of [acc.text,acc.notifications[0].response.text])assert.doesNotMatch(t,/חסוי/);});
test("board copy: no stale phone-privacy line, list rows never show 24:00",async()=>{const s=memoryStore();await setName(s,"יוסי");await say(s,{actionId:"oneoff"});await register(s);const b=await say(s,{text:"מי מחפש משחק מחר בערב?"},"972529999999");assert.doesNotMatch(b.text,/אינם מוצגים|חסוי/);assert.match(b.text,/להתחברות בחרו בקשה מהרשימה\./);for(const r of b.list.sections.flatMap(x=>x.rows))assert.doesNotMatch(r.description||"",/24:00/);});
