import test from "node:test";import assert from "node:assert/strict";
import {deliver,windowOpen,recordInbound,MATCH_TEMPLATE,WINDOW_MS} from "../src/notify.js";
import {routeIncoming} from "../src/webhook.js";import {sendTemplate} from "../src/whatsapp.js";import {messageInput} from "../netlify/functions/whatsapp.js";
import {memoryStore} from "../src/store.js";
const now=new Date("2026-09-23T10:00:00+03:00"),ago=ms=>new Date(now.getTime()-ms);
const U="972501111111",R={text:"מצאתי התאמה אפשרית: דנה · 2026-09-24 · רמה 3–3.5. תרצו להתחבר?",buttons:[{id:"connect:req1",title:"רוצה להתחבר"}]};
function spies(){const calls={send:[],template:[]};return{calls,send:async(to,r)=>{calls.send.push({to,r});return{sent:true};},sendTemplate:async(to,t)=>{calls.template.push({to,t});return{sent:true};}};}
test("window: open under 24h, closed at exactly 24h and beyond, closed when never seen",()=>{assert(windowOpen({lastInboundAt:ago(WINDOW_MS-60000).toISOString()},now));assert(!windowOpen({lastInboundAt:ago(WINDOW_MS).toISOString()},now));assert(!windowOpen({lastInboundAt:ago(3*WINDOW_MS).toISOString()},now));assert(!windowOpen(null,now));});
test("inside the window: free-form message, no template, nothing pending",async()=>{const s=memoryStore(),x=spies();await recordInbound(s,U,ago(3600000));const d=await deliver(s,U,R,{now,...x});assert.equal(d.mode,"freeform");assert.equal(x.calls.send.length,1);assert.equal(x.calls.template.length,0);assert.equal(await s.get(`pending/${U}`),null);});
test("outside the window: approved template only, full notification kept pending",async()=>{const s=memoryStore(),x=spies();await recordInbound(s,U,ago(WINDOW_MS+1));const d=await deliver(s,U,R,{now,...x});assert.equal(d.mode,"template");assert.equal(x.calls.send.length,0);assert.deepEqual(x.calls.template[0].t,MATCH_TEMPLATE);assert.equal((await s.get(`pending/${U}`)).items[0].response.text,R.text);});
test("never-seen user gets the template path",async()=>{const s=memoryStore(),x=spies();const d=await deliver(s,U,R,{now,...x});assert.equal(d.mode,"template");});
test("a second match outside the window within 24h does not send another template; both are kept",async()=>{const s=memoryStore(),x=spies();await deliver(s,U,R,{now,...x});await deliver(s,U,{...R,text:"שנייה"},{now:new Date(now.getTime()+3600000),...x});assert.equal(x.calls.template.length,1);assert.equal((await s.get(`pending/${U}`)).items.length,2);});
test("template payload: approved name, Hebrew, quick-reply payloads only - no names, numbers or match details",async()=>{process.env.DISABLE_OUTBOUND="false";process.env.WHATSAPP_ACCESS_TOKEN="t";process.env.WHATSAPP_PHONE_NUMBER_ID="p";let body;await sendTemplate(U,MATCH_TEMPLATE.name,MATCH_TEMPLATE.language,MATCH_TEMPLATE.payloads,undefined,async(url,init)=>{body=JSON.parse(init.body);return{ok:true,json:async()=>({})};});process.env.DISABLE_OUTBOUND="true";assert.equal(body.type,"template");assert.equal(body.template.name,"gt_match_found_v2");assert.equal(body.template.language.code,"he");assert.deepEqual(body.template.components.map(c=>c.parameters[0].payload),["pending_yes","pending_no"]);const rest=JSON.stringify(body.template);assert.doesNotMatch(rest,/05\d|דנה|3–3\.5|2026/);});
test("template button tap arrives as a payload and routes into the bot",()=>{assert.deepEqual(messageInput({type:"button",button:{payload:"pending_yes",text:"כן, שלחו פרטים"}}),{actionId:"pending_yes",text:"כן, שלחו פרטים"});});
test("every inbound message records the last-inbound time (reopens the window)",async()=>{const s=memoryStore();await routeIncoming({userId:U,text:"שלום",store:s,now});assert.equal((await s.get(`profile/${U}`)).lastInboundAt,now.toISOString());});
test("tapping yes batches pending offers in one actionable list and preserves other offers",async()=>{const s=memoryStore(),x=spies();await deliver(s,U,R,{now,...x});await deliver(s,U,{...R,text:'מצאתי התאמה אפשרית: רון',buttons:[{id:'connect:req2',title:'רוצה להתחבר'},{id:'notnow:req2',title:'לא הפעם'}]},{now,...x});const r=await routeIncoming({userId:U,actionId:'pending_yes',store:s,now});assert.equal(r.notifications?.length||0,0);assert.equal(r.list?.button,'בחר');const rows=r.list.sections[0].rows;assert.equal(rows.filter(x=>x.id.startsWith('pending_connect:')).length,2);assert.equal(rows.filter(x=>x.id.startsWith('pending_skip:')).length,2);assert.match(r.text,/דנה/);assert.match(r.text,/רון/);assert.equal((await s.get(`pending/${U}`)).items.length,2);
 const skip=await routeIncoming({userId:U,actionId:rows.find(x=>x.id.startsWith('pending_skip:')).id,store:s,now});assert.match(skip.text,/לא אציע לכם/);assert.equal((await s.get(`pending/${U}`)).items.length,1);const stale=await routeIncoming({userId:U,actionId:rows.find(x=>x.id.startsWith('pending_skip:')).id,store:s,now});assert.match(stale.text,/לא זמינה/);assert.equal((await s.get(`pending/${U}`)).items.length,1);const remaining=await routeIncoming({userId:U,text:'ההתאמות שלי',store:s,now});assert.equal(remaining.list?.sections[0].rows.filter(x=>x.id.startsWith('pending_connect:')).length,1);assert.equal((await s.get(`pending/${U}`)).items.length,1);});

test("typing 'כן' with a pending match delivers it; 'כן' without one routes normally",async()=>{const s=memoryStore(),x=spies();await deliver(s,U,R,{now,...x});const r=await routeIncoming({userId:U,text:"כן",store:s,now});assert.equal(r.text,R.text);const again=await routeIncoming({userId:U,text:"כן",store:s,now});assert.notEqual(again.text,R.text);});
test("'לא עכשיו' clears the pending match without sending details",async()=>{const s=memoryStore(),x=spies();await deliver(s,U,R,{now,...x});const r=await routeIncoming({userId:U,actionId:"pending_no",store:s,now});assert.match(r.text,/לא אשלח/);assert.equal(await s.get(`pending/${U}`),null);});
test("tapping yes with nothing pending says so",async()=>{const r=await routeIncoming({userId:U,actionId:"pending_yes",store:memoryStore(),now});assert.match(r.text,/אין כרגע התאמות שממתינות לך/);});
test("a pending match whose request expired answers 'no longer active' on connect",async()=>{const s=memoryStore();await s.set(`profile/${U}`,{userId:U,name:"יוסי"});const r=await routeIncoming({userId:U,actionId:"connect:gone",store:s,now});assert.match(r.text,/הבקשה כבר לא פעילה/);});
test('pending batches paginate without dropping offers or exceeding Meta list limits',async()=>{
 const s=memoryStore(),x=spies();for(let i=0;i<11;i++)await deliver(s,U,{text:`מצאתי התאמה אפשרית: שחקן ${i} · רמה 3 · מחר ב-19:00`,buttons:[{id:`connect:req${i}`,title:'רוצה להתחבר'},{id:`notnow:req${i}`,title:'לא הפעם'}]},{now,...x});
 assert.equal((await s.get(`pending/${U}`)).items.length,11);
 const p1=await routeIncoming({userId:U,actionId:'pending_yes',store:s,now});const rows1=p1.list.sections[0].rows;assert(rows1.length<=10);assert(p1.text.length<=1024);assert.equal(rows1.filter(r=>r.id.startsWith('pending_connect:')).length,3);assert(rows1.every(r=>r.id.length<=200));const next=rows1.find(r=>r.id.startsWith('pending_page:'));assert(next);
 const p2=await routeIncoming({userId:U,actionId:next.id,store:s,now});assert.equal(p2.list.sections[0].rows.filter(r=>r.id.startsWith('pending_connect:')).length,3);assert(p2.text.length<=1024);
 const p3=await routeIncoming({userId:U,actionId:p2.list.sections[0].rows.find(r=>r.id.startsWith('pending_page:')).id,store:s,now});assert.equal(p3.list.sections[0].rows.filter(r=>r.id.startsWith('pending_connect:')).length,3);const p4=await routeIncoming({userId:U,actionId:p3.list.sections[0].rows.find(r=>r.id.startsWith('pending_page:')).id,store:s,now});assert.equal(p4.list.sections[0].rows.filter(r=>r.id.startsWith('pending_connect:')).length,2);assert.equal((await s.get(`pending/${U}`)).items.length,11);
});
test('batch list follows production message encoder, preserves request identity and club boundary through flow end',async()=>{
 const {sendResponse}=await import('../src/whatsapp.js');const {SAAR_VENUE,SMASH_VENUE,assertVenueResponse}=await import('../src/venues.js');
 const old=process.env.DISABLE_OUTBOUND;process.env.DISABLE_OUTBOUND='false';process.env.WHATSAPP_ACCESS_TOKEN='capture-only';process.env.WHATSAPP_PHONE_NUMBER_ID='capture-phone';
 try{for(const venue of [SAAR_VENUE,SMASH_VENUE]){
  const s=memoryStore(),userId=`972500000${venue.key==='saar'?'101':'102'}`,r1={text:`מצאתי התאמה אפשרית: דנה · ${venue.name} · מחר 19:00`,buttons:[{id:'connect:missing1',title:'רוצה להתחבר'},{id:'notnow:missing1',title:'לא הפעם'}]},r2={text:`מצאתי התאמה אפשרית: רון · ${venue.name} · מחר 20:00`,buttons:[{id:'connect:missing2',title:'רוצה להתחבר'},{id:'notnow:missing2',title:'לא הפעם'}]};
  await deliver(s,userId,r1,{now,venue,...spies()});await deliver(s,userId,r2,{now,venue,...spies()});
  const reply=await routeIncoming({userId,actionId:'pending_yes',store:s,venue,now});assertVenueResponse(venue,reply);
  const payloads=[];await sendResponse(userId,reply,'capture-phone',async(_url,opt)=>(payloads.push(JSON.parse(opt.body)),{ok:true,json:async()=>({messages:[{id:'captured'}]})}));
  assert.equal(payloads.length,1);assert.equal(payloads[0].interactive.type,'list');assert.equal(payloads[0].interactive.action.sections[0].rows.length,5);assert.match(payloads[0].interactive.body.text,/דנה/);assert.match(payloads[0].interactive.body.text,/רון/);assert.doesNotMatch(JSON.stringify(payloads[0]),/GT PADEL|גני תקווה/);
  const ids=payloads[0].interactive.action.sections[0].rows.map(x=>x.id);for(const id of ids.filter(x=>x.startsWith('pending_skip:'))){const result=await routeIncoming({userId,actionId:id,store:s,venue,now});assert.match(result.text,/לא אציע לכם/);assertVenueResponse(venue,result);}
  assert.equal(await s.get(`pending/${userId}`),null);
 }}finally{if(old===undefined)delete process.env.DISABLE_OUTBOUND;else process.env.DISABLE_OUTBOUND=old;}
});
