import { getStore } from "@netlify/blobs";
import { BUILD } from "../../src/build-info.js";
import {SAAR_VENUE,SMASH_VENUE,isolatedStoreName} from "../../src/venues.js";
// lastReset: when the data was last wiped and how many keys were removed (counts only, no content).
export default async () => {let lastReset=null,lastSeed=null,lastDemo=null,lastDiag=null,lastCourtTemplate=null,lastCourtBookingTemplate=null,lastWabaBillingDiagnostic=null,lastCourtScan=null,lastCourtReleases=[],otherCourtScans={};try{const st=getStore({name:"gt-padel-matching",consistency:"strong"});lastReset=await st.get("meta/last-reset",{type:"json"});lastSeed=await st.get("meta/last-seed",{type:"json"});lastDemo=await st.get("meta/last-demo",{type:"json"});lastDiag=await st.get("meta/last-diag",{type:"json"});lastCourtTemplate=await st.get("meta/court-template",{type:"json"});lastCourtBookingTemplate=await st.get("meta/court-booking-template",{type:"json"});lastWabaBillingDiagnostic=await st.get("meta/waba-billing-diagnostic",{type:"json"});
  lastCourtScan=await st.get("meta/court-release-scan",{type:"json"});
  const listed=await st.list({prefix:"court-release/outbox/"});
  for(const item of listed.blobs.slice(0,250)){const row=await st.get(item.key,{type:"json"});if(row?.detectedAt)lastCourtReleases.push({venue:row.window?.venueName,date:row.window?.date,court:row.window?.courtName,startMinute:row.window?.startMinute,endMinute:row.window?.endMinute,detectedAt:row.detectedAt,status:row.status});}
  lastCourtReleases.sort((a,b)=>b.detectedAt.localeCompare(a.detectedAt));lastCourtReleases=lastCourtReleases.slice(0,50);}catch{}
 for(const club of [SAAR_VENUE,SMASH_VENUE])try{const row=await getStore({name:isolatedStoreName(club),consistency:"strong"}).get("meta/court-release-scan",{type:"json"});otherCourtScans[club.key]=row?{status:row.status,mode:row.mode,venue:row.venue,at:row.at,windows:row.windows,sent:row.sent,failed:row.failed}:null;}catch{otherCourtScans[club.key]={status:"unavailable"};}
 return new Response(JSON.stringify({ok:true,service:"gt-padel-agent",build:BUILD,lastReset,lastSeed,lastDemo,lastDiag,lastCourtTemplate,lastCourtBookingTemplate,lastWabaBillingDiagnostic,lastCourtScan,lastCourtReleases,otherCourtScans}),{headers:{"content-type":"application/json"}});};
