import {PREVIEW_BUILD} from '../src/preview-build.js';
// Owner-only, one-card-at-a-time review. Every visible candidate has passed conservative redaction.
const CSS=`:root{font-family:Arial,sans-serif;color:#13213b;background:#f3f6fc}*{box-sizing:border-box}body{margin:0}main{max-width:680px;margin:auto;padding:24px 16px 60px}h1{font-size:26px;margin:0 0 8px}p{line-height:1.55}.muted{color:#536177}.card{background:white;border:1px solid #dce4ee;border-radius:18px;padding:22px;margin:20px 0;box-shadow:0 3px 16px #d8e1ec55}.badge{background:#e7efff;color:#1b478c;border-radius:8px;padding:6px 10px;display:inline-block;font-size:13px}.phrase{font-size:23px;line-height:1.5;overflow-wrap:anywhere;margin:22px 0}button,input{font:inherit}button{border:1px solid #bdcae1;background:white;border-radius:12px;padding:14px;cursor:pointer;color:#153053}button:hover,button:focus{border-color:#215ccc;background:#f2f6ff}button:disabled{opacity:.55;cursor:not-allowed}.choices{display:grid;grid-template-columns:1fr 1fr;gap:10px}.choices button{min-height:58px;text-align:right}.choices button.selected{background:#dceaff;border-color:#215ccc;font-weight:bold}.bar{height:9px;background:#dbe3ee;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:#245ec7}.row{display:flex;gap:10px;align-items:center;justify-content:space-between}.small{font-size:14px}.secondary{border:0;background:transparent;padding:8px}.error{color:#ae1937}.success{color:#176740}#login input{padding:14px;width:100%;border:1px solid #9eadc3;border-radius:10px;margin:10px 0}@media(max-width:420px){main{padding:16px 12px}.choices{grid-template-columns:1fr 1fr}.choices button{font-size:15px;min-height:58px}.phrase{font-size:20px}}`;
const JS=`const L=[['availability','מגרש פנוי'],['public_board','לוח משחקים'],['player_search','חיפוש שחקנים'],['unknown','לא ברור'],['other','אחר']];
let token=sessionStorage.getItem('gt-routing-label-token')||'',data=null,index=0,review=false,busy=false;
const $=id=>document.getElementById(id),esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(method,body){let r=await fetch('/.netlify/functions/routing-label-api',{method,headers:{authorization:'Bearer '+token,...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(!r.ok)throw Error(r.status===401?'סיסמה שגויה או שפג תוקף החיבור':r.status===429?'יותר מדי ניסיונות. נסו שוב מאוחר יותר':'לא הצלחנו לטעון את הדוגמאות');return r.json()}
async function start(){token=$('pw').value.trim();$('err').textContent='';try{data=await api('GET');sessionStorage.setItem('gt-routing-label-token',token);$('login').hidden=true;$('work').hidden=false;render()}catch(e){$('err').textContent=e.message;token=''}}
async function reload(){try{data=await api('GET');render()}catch(e){$('notice').textContent=e.message}}
function render(){if(!data)return;const items=data.items;index=Math.min(index,Math.max(0,items.length-1));const done=data.done,score=data.score?.pooled;
 $('progress').textContent=done+' / '+data.total+' תויגו · '+data.eligible+' ניסוחים זכאים';$('meter').style.width=(data.total?Math.round(100*done/data.total):0)+'%';$('summary').textContent=score?.n?('דיוק ראשוני: '+score.correct+' / '+score.n+' ('+Math.round(100*score.accuracy)+'%)'): 'עדיין אין מספיק תוויות למדידת דיוק';
 $('toggle').textContent=review?'חזרה לתיוג':'סקירה';
 if(review){$('content').innerHTML='<div class="card"><h2>סקירת תוויות</h2>'+items.map((item,i)=>'<p><button class="secondary" data-jump="'+i+'">'+(i+1)+'. '+esc(item.text)+'</button><br><span class="muted">'+esc(item.label?L.find(x=>x[0]===item.label)?.[1]:'לא תויג')+'</span></p>').join('')+'</div>';return}
 const x=items[index];if(!x){$('content').innerHTML='<div class="card">אין כרגע הודעות מתאימות לתייג. כשתגיענה הודעות טקסט חדשות אפשר לרענן.</div>';return}
 $('content').innerHTML='<div class="card"><div class="row"><span class="badge">'+esc(x.clubs.join(' · '))+'</span><span class="muted small">'+(index+1)+' / '+items.length+'</span></div><div class="phrase">'+esc(x.text)+'</div><p class="muted small">טקסט בלבד, ללא פרטי שיחה או משתמש. אם חסר הקשר, בחרו "צריך הקשר".</p><div class="choices">'+L.map(([v,name])=>'<button data-label="'+v+'" class="'+(x.label===v?'selected':'')+'">'+name+'</button>').join('')+'</div><div class="row" style="margin-top:18px"><button class="secondary" data-skip="1">דילוג</button><button class="secondary" data-context="1">צריך הקשר</button></div></div><div class="row"><button data-prev="1" '+(index?'':'disabled')+'>הקודם</button><button data-next="1" '+(index<items.length-1?'':'disabled')+'>הבא</button></div>';
}
async function save(label,needsContext=false){if(busy)return;busy=true;$('notice').textContent='';try{await api('POST',{id:data.items[index].id,label,needsContext});await reload();if(index<data.items.length-1)index++;render()}catch(e){$('notice').textContent=e.message}finally{busy=false}}
$('content').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.label)save(b.dataset.label);else if(b.dataset.context)save(null,true);else if(b.dataset.skip){if(index<data.items.length-1)index++;render()}else if(b.dataset.prev){index--;render()}else if(b.dataset.next){index++;render()}else if(b.dataset.jump){index=Number(b.dataset.jump);review=false;render()}};
$('toggle').onclick=()=>{review=!review;render()};$('refresh').onclick=reload;$('enter').onclick=start;$('pw').onkeydown=e=>{if(e.key==='Enter')start()};
if(token)api('GET').then(x=>{data=x;$('login').hidden=true;$('work').hidden=false;render()}).catch(()=>{token='';sessionStorage.removeItem('gt-routing-label-token')});`;
export function routingLabelPage(){if(!PREVIEW_BUILD)return new Response('not found',{status:404});return new Response(`<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>תיוג כוונות - פאדל</title><style>${CSS}</style></head><body><main><h1>תיוג הודעות לפאדל</h1><p class="muted">דוגמאות מסוננות מהפיילוט, מכל המועדונים. בוחרים מה הבוט אמור להבין, לא מה הוא ענה בפועל.</p><section class="card" id="login"><label for="pw">סיסמת ניהול גני תקווה</label><input id="pw" type="password" autocomplete="current-password"><button id="enter">כניסה</button><p class="error" id="err" role="alert"></p></section><section id="work" hidden><div class="row"><b id="progress"></b><button id="refresh" class="secondary">רענון</button></div><div class="bar"><i id="meter"></i></div><p id="summary" class="muted"></p><button id="toggle" class="secondary">סקירה</button><p class="error" id="notice" role="alert"></p><div id="content"></div></section></main><script>${JS}</script></body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'",'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer'}})}
export default routingLabelPage;
