import { CONFIG } from "./config.js";
import { staticData, occupied } from "./matchpointer.js";
import { addDays, hhmm, min, rangesFor, weekdayIndex } from "./time.js";
const overlaps=(a,b,c,d)=>a<d&&c<b;
const heDate=iso=>new Intl.DateTimeFormat("he-IL",{timeZone:CONFIG.timezone,weekday:"long",day:"numeric",month:"numeric"}).format(new Date(`${iso}T12:00:00Z`)).replace(",","");
// Mirrors the Matchpointer booking page (ClubPage Ps/ur/dr/Je): date override first, shortest matching rule wins; a 90/120 price applies only when the game fits inside that rule, otherwise each segment is priced pro rata by the rule in force at that minute.
const pickShortest=list=>list.length?[...list].sort((a,b)=>(min(a.end_time)-min(a.start_time))-(min(b.end_time)-min(b.start_time)))[0]:null;
function ruleAt(data,courtId,date,minute){const t=`${hhmm(minute)}:00`,inR=r=>!(t<String(r.start_time).padEnd(8,":00").slice(0,8)||t>=String(r.end_time).padEnd(8,":00").slice(0,8));const ov=(data.overrides||[]).filter(r=>r.override_date===date&&inR(r));if(ov.length){const own=ov.filter(r=>r.court_id===courtId);return pickShortest(own.length?own:ov.filter(r=>!r.court_id));}const dow=weekdayIndex(date),w=(data.pricing||[]).filter(r=>inR(r)&&(r.day_of_week==null||r.day_of_week===dow));for(const f of [r=>r.court_id===courtId&&r.day_of_week!=null,r=>r.court_id===courtId&&r.day_of_week==null,r=>!r.court_id&&r.day_of_week!=null,r=>!r.court_id&&r.day_of_week==null]){const m=w.filter(f);if(m.length)return pickShortest(m);}return null;}
export function priceFor(data,courtId,date,start,duration){const r=ruleAt(data,courtId,date,start);if(!r)return null;const end=start+duration;if(duration===90&&r.price_90!=null&&end<=min(r.end_time))return Number(r.price_90);if(duration===120&&r.price_120!=null&&end<=min(r.end_time))return Number(r.price_120);let total=0,left=duration,cur=start;while(left>0){const rule=ruleAt(data,courtId,date,cur);const p=Number(rule?.price);if(!rule||!(p>0))return null;const seg=Math.min(60-(cur%60),left);total+=p*seg/60;left-=seg;cur+=seg;}return Math.round(total*100)/100;}
// Matchpointer hides a start that would strand a lone 30-minute cell before or after the game (venue.allow_unbookable_time=false; ClubPage ss()). A deep link to such a time lands on a different preselected time, so never offer it.
export function leavesOrphan(venue,busy,courtId,date,start,end,range,{nowMinute=null}={}){if(venue?.allow_unbookable_time!==false)return false;const open=min(range.openTime),close=min(range.closeTime),occ=m=>busy.some(b=>b.court_id===courtId&&b.date===date&&min(b.start_time)<=m&&m<min(b.end_time));const ce=start-30;if(ce>=open&&!(nowMinute!=null&&ce<nowMinute)){if(!occ(ce)&&(ce===open||occ(ce-30)))return true;}if(end+30<=close){if(!occ(end)&&(end+30===close||occ(end+30)))return true;}return false;}
export async function findAvailability(intent,{fetchImpl=fetch,today,now}={}){const data=await staticData(fetchImpl);const clock=now instanceof Date?now:new Date(now??Date.now());const base=today||new Intl.DateTimeFormat("en-CA",{timeZone:CONFIG.timezone}).format(clock);const [ch,cm]=new Intl.DateTimeFormat("en-GB",{timeZone:CONFIG.timezone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(clock).split(":").map(Number),earliest=intent.date===base&&!today?ch*60+cm:0;if(intent.date<base||intent.date>addDays(base,data.venue.advance_booking_days??CONFIG.advanceDays))return{kind:"outside_window",date:intent.date,advanceDays:data.venue.advance_booking_days??CONFIG.advanceDays,slots:[]};const busy=await occupied(intent.date,intent.date,data.courts.map(c=>c.id),fetchImpl);const duration=intent.durationMinutes||60,slots=[];for(const court of data.courts)for(const range of rangesFor(data.venue,intent.date)){const lo=Math.max(min(range.openTime),intent.startMinute??0,earliest),hi=Math.min(min(range.closeTime),intent.endMinute??1440);for(let start=Math.ceil(lo/30)*30;start+duration<=hi;start+=30){if(busy.some(b=>b.court_id===court.id&&b.date===intent.date&&overlaps(start,start+duration,min(b.start_time),min(b.end_time))))continue;if(leavesOrphan(data.venue,busy,court.id,intent.date,start,start+duration,range,{nowMinute:intent.date===base&&!today?earliest:null}))continue;slots.push({courtId:court.id,courtName:court.name,start:hhmm(start),end:hhmm(start+duration),durationMinutes:duration,price:priceFor(data,court.id,intent.date,start,duration)});}}return{kind:"availability",date:intent.date,slots};}
export function bookingUrl(date,slot,{source="availability",user=null}={}){if(!slot?.courtId||!slot?.start||!slot?.durationMinutes)return null;const q=new URLSearchParams({court:slot.courtId,time:slot.start,date,duration:String(slot.durationMinutes),step:"confirm"});const target=`${CONFIG.siteOrigin}/he/clubs/${CONFIG.venueSlug}/book?${q}`;const tracking=new URLSearchParams({target,source,date,court:slot.courtId,time:slot.start,duration:String(slot.durationMinutes),price:String(slot.price??"")});if(user&&/^\d{6,15}$/.test(String(user)))tracking.set("user",String(user));return `${process.env.PUBLIC_SITE_URL||"https://gtpadel.netlify.app"}/go/book?${tracking}`;}
function grouped(slots){const map=new Map();for(const s of slots){const key=`${s.start}-${s.end}-${s.price??"?"}`;const g=map.get(key)||{start:s.start,end:s.end,price:s.price,courts:[],bookingSlot:s};g.courts.push(s.courtName);map.set(key,g);}return[...map.values()].sort((a,b)=>a.start.localeCompare(b.start));}
export function formatHebrew(result,{maxGroups=2}={}){
  if(result.kind==="outside_window")return `אפשר לבדוק זמינות עד ${result.advanceDays} ימים קדימה. איזה יום קרוב יותר מתאים לך?`;
  const label=heDate(result.date); if(!result.slots.length)return `אין מגרש פנוי ב${label} בטווח שביקשת, וגם לא בשאר היום. אפשר לבדוק יום אחר, למשל "מחר בערב".`;
  const groups=grouped(result.slots),shown=groups.slice(0,maxGroups);const lines=shown.map(g=>{const courtText=g.courts.length===3?"כל 3 המגרשים":g.courts.length===1?`מגרש ${g.courts[0]}`:`מגרשים ${g.courts.join(", ")}`;const link=bookingUrl(result.date,g.bookingSlot);return `• ${g.start}–${g.end} · ${courtText}${g.price!=null?` · ₪${g.price}`:""}`;});
  const listed=Math.min(groups.length,MAX_SLOT_ROWS),more=listed-shown.length;const tail=(more>0?`\nועוד ${more===1?"אפשרות אחת":`${more} אפשרויות`} ברשימה.`:"")+(groups.length>MAX_SLOT_ROWS?`\nלאפשרויות נוספות כתבו טווח מדויק יותר, למשל "אחרי 20:00".`:"");
  return `יש זמינות ב${label}:\n${lines.join("\n")}${tail}`;
}

export async function findAvailabilitySeries(intent,opts={}){const dates=intent.dates?.length?intent.dates:[intent.date];return Promise.all(dates.map(date=>findAvailability({...intent,date,dates:undefined},opts)));}
export function formatHebrewSeries(results,options={}){if(results.length===1)return formatHebrew(results[0],options);const sections=results.map(r=>{const label=heDate(r.date);if(r.kind==="outside_window")return null;if(!r.slots.length)return `*${label}*\nלא נמצאה זמינות בטווח שביקשת.`;const lines=grouped(r.slots).slice(0,1).map(g=>{const courts=g.courts.length===3?"כל 3 המגרשים":g.courts.length===1?`מגרש ${g.courts[0]}`:`מגרשים ${g.courts.join(", ")}`;const link=bookingUrl(r.date,g.bookingSlot);return `• ${g.start}–${g.end} · ${courts}${g.price!=null?` · ₪${g.price}`:""}`;});return `*${label}*\n${lines.join("\n")}`;}).filter(Boolean);return `${sections.join("\n\n")}`;}

export const MAX_SLOT_ROWS=9;
const courtsLabel=g=>g.courts.length===3?"כל 3 המגרשים":g.courts.length===1?`מגרש ${g.courts[0]}`:`מגרשים ${g.courts.join(", ")}`;
const shortDate=iso=>`${Number(iso.slice(8,10))}.${Number(iso.slice(5,7))}`;
// Live 23.9 12:45: base64 of the tracking URL made row ids 455 chars; Meta rejects list row ids over 200 (#131009) and the reply was silently lost.
// Compact ASCII id instead; the URL is rebuilt on tap. Always well under 200.
export function slotActionId(date,slot){return `bk:${date}.${slot.courtId}.${String(slot.start).replace(":","")}.${slot.durationMinutes}.${slot.price??""}`;}
export function slotFromActionId(id){const m=/^bk:(\d{4}-\d{2}-\d{2})\.([^.]+)\.(\d{4})\.(\d+)\.(\d*(?:\.\d+)?)$/.exec(id||"");if(!m)return null;return{date:m[1],slot:{courtId:m[2],start:`${m[3].slice(0,2)}:${m[3].slice(2)}`,durationMinutes:Number(m[4]),price:m[5]===""?undefined:Number(m[5])}};}
export function availabilityChoices(results,{maxRows=MAX_SLOT_ROWS,groupsFor}={}){const rows=[];const multi=results.filter(r=>r.kind==="availability"&&r.slots.length).length>1;for(const result of results){if(result.kind!=="availability")continue;const groups=groupsFor?groupsFor(result):grouped(result.slots);for(const g of groups){if(rows.length>=maxRows)return rows;const url=bookingUrl(result.date,g.bookingSlot);if(!url)continue;const title=`${multi?shortDate(result.date)+" ":""}${g.start}–${g.end}`;rows.push({id:slotActionId(result.date,g.bookingSlot),title:title.slice(0,24),description:`${courtsLabel(g)}${g.price!=null?` · ₪${g.price}`:""}`.slice(0,72),start:g.start,url});}}return rows;}
export function groupedSlots(slots){return grouped(slots);}


export function nearestGroups(result,intent,count=3){const lo=intent.startMinute??0,hi=intent.endMinute??1440,dist=g=>{const a=min(g.start),b=min(g.end);return a>=lo&&b<=hi?0:a<lo?lo-a:a-hi;};return grouped(result.slots).map(g=>({g,d:dist(g)})).sort((x,y)=>x.d-y.d||x.g.start.localeCompare(y.g.start)).slice(0,count).map(x=>x.g).sort((a,b)=>a.start.localeCompare(b.start));}
export function formatNearest(result,groups){const label=heDate(result.date);return `אין מגרש פנוי ב${label} בטווח שביקשת. השעות הכי קרובות באותו יום:\n${groups.map(g=>`• ${g.start}–${g.end} · ${courtsLabel(g)}${g.price!=null?` · ₪${g.price}`:""}`).join("\n")}`;}
