import { UNCLEAR_WHEN } from "./timeres.js";
import { MAX_ACTIVE_REQUESTS, reqTitle, reqDesc, userActiveRequests, lastRequest } from "./requests.js";
import crypto from "node:crypto";
import { parseIntentLocal } from "./intent.js";
import { parseWhen, whenLabel as whenEcho } from "./when.js";
import { findAvailability } from "./availability.js";
import { activeRequests, DURATIONS, findMatches, formatBoard, LEVELS, levelTitle, levelNote, flexMinutesFor, mute, publicBoard, welcome, formatPhone, clockLabel } from "./matching.js";
// Row/button ids stay ASCII (index-based); Hebrew labels live only in titles. Tom 23.9: list taps went undelivered.
const WHEN_OPTIONS=["היום בערב","מחר בבוקר","מחר בערב","שישי בבוקר","שבת בבוקר"];
const whenLabel=v=>/^\d+$/.test(v)?WHEN_OPTIONS[Number(v)]||"":v;
const levelValue=v=>/^\d+$/.test(v)?LEVELS[Number(v)]:v;
const btn=(text,buttons)=>({text,buttons:buttons.map(x=>typeof x==="string"?{id:x,title:x}:x)}), list=(text,items)=>({text,list:{button:"לבחירה",sections:[{title:"אפשרויות",rows:items}]}});
const id=()=>crypto.randomUUID();
const MY_REQ={id:"my_requests",title:"הבקשות שלי"},MENU={id:"menu",title:"לתפריט"};
const LEVEL_ROWS=()=>LEVELS.map((x,i)=>({id:`level:${i}`,title:levelTitle(x)}));
const DURATION_ROWS=()=>DURATIONS.map(d=>({id:`duration:${d}`,title:`${d} דקות`})).concat({id:"duration:flex",title:"גמיש"});
const PARTY_ROWS=()=>[{id:"party:1",title:"רק אני"},{id:"party:2",title:"אני ועוד אחד"},{id:"party:3",title:"שלושה, מחפשים רביעי"}];
const FLEX_ROWS=()=>[{id:"flex:0",title:"שעה מדויקת"},{id:"flex:60",title:"שעה"},{id:"flex:any",title:"גמיש"}];
const CAP_TEXT=`יש לך כבר ${MAX_ACTIVE_REQUESTS} בקשות פעילות. אפשר למחוק אחת דרך 'הבקשות שלי'.`;
const matchLines=(request,matches)=>matches.length?`\n\nמצאתי ${matches.length} התאמות אפשריות ושלחתי הצעה:\n${matches.slice(0,3).map(m=>`• ${m.displayName} · רמה ${m.level}${levelNote(request.level,m.level)}`).join("\n")}`:"";
const matchNotifications=(request,matches)=>matches.slice(0,3).map(m=>({to:m.userId,response:btn(`מצאתי התאמה אפשרית: ${request.displayName} · ${request.date} · רמה ${request.level}${levelNote(m.level,request.level)}. תרצו להתחבר?`,[{id:`connect:${request.id}`,title:"רוצה להתחבר"},{id:"mute_week",title:"השתקה לשבוע"},{id:"mute_custom",title:"השתקה אחרת"}])}));
// Tom-approved copy 23.9 10:28 (+emoji per option).
export const PLAYERS_MENU="מה בא לכם?\n\n👥 חסרים לי שחקנים - יש לכם מגרש וזמן, וחסרים שחקנים להשלמת רביעייה.\n\n⚡ להצטרף למשחק חד-פעמי - רוצים לראות משחקים פתוחים ולהצטרף.\n\n🔁 משחק קבוע כל שבוע - רושמים פעם אחת את הזמנים שנוחים, וכל שבוע המערכת תנסה לשדך לכם שחקנים. בלי התחייבות - אפשר לעדכן או להסיר בכל רגע.";
const NAME_ASK="מה השם שלך? כך תופיעו בלוח המשחקים.";
export function cleanName(raw){let t=String(raw||"").replace(/^(אני\s+)?(קוראים לי|שמי|השם שלי(?:\s+הוא)?|תקרא(?:ו)? לי|תקראי לי)\s*/,"").replace(/[.!?,"'״׳:;()]/g," ").replace(/\s+/g," ").trim();if(!t||t.length>30||/\d|@/.test(t)||t.split(" ").length>3)return null;if(/^(לא|כן|תפריט|שלום|היי|הי|אוקי|בסדר|menu|hi)$/i.test(t))return null;if(t.split(" ").some(w=>/^(מה|איך|מתי|כמה|איפה|למה|מי|יש|אין|רוצה|רוצים|מגרש|מגרשים|משחק|שחקן|שחקנים|פנוי|מחר|היום|בערב|בבוקר|תודה|אפשר|צריך|בוקר|ערב|טוב|קורה|שלום)$/.test(w)))return null;return t;}
export function nameChangeIntent(text){const t=String(text||"").trim();if(!t)return null;let m=t.match(/^(?:אני\s+)?(?:קוראים לי|שמי)\s+(.+)$/);if(m)return{name:cleanName(m[1])};if(/השם שלי(?:\s+הוא)?\s+לא(?:\s|$)/.test(t))return{name:null};m=t.match(/(?:לשנות|לעדכן|להחליף|תשנה|תעדכן|תחליף|שנה|תחליפו|תשנו)\s+(?:לי\s+)?(?:את\s+)?(?:ה)?שם(?:\s+שלי)?(?:\s+ל[-־]?\s*(\S.*))?$/);if(m)return{name:m[1]?cleanName(m[1]):null};m=t.match(/^(?:אבל\s+)?השם שלי(?:\s+הוא)?\s+(?!לא(?:\s|$))(.+)$/);if(m)return{name:cleanName(m[1])};if(/השם שלי(?:\s+הוא)?\s+לא(?:\s|$)/.test(t)||/(?:לשנות|לעדכן|שינוי|עדכון|להחליף)\s+(?:את\s+)?(?:ה)?שם/.test(t)||/השם\s+(?:שלי\s+)?לא\s+נכון/.test(t))return{name:null};return null;}
const NEXT_WEEK=/(?:ב|ל)?שבוע ה(?:בא|קרוב)/;
const HE_DAYS=["ראשון","שני","שלישי","רביעי","חמישי","שישי","שבת"];
export function nextWeekDays(now){const t=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jerusalem"}).format(now),base=new Date(`${t}T12:00:00Z`),dow=base.getUTCDay(),out=[];for(let i=0;i<7;i++){const d=new Date(base.getTime()+((7-dow)+i)*86400000);out.push({date:d.toISOString().slice(0,10),ddmm:`${d.getUTCDate()}.${d.getUTCMonth()+1}`,label:`${HE_DAYS[d.getUTCDay()]} ${d.getUTCDate()}.${d.getUTCMonth()+1}`});}return out;}
const WD=new Map([["ראשון",0],["שני",1],["שלישי",2],["רביעי",3],["חמישי",4],["שישי",5],["שבת",6]]);
const recurringDays=text=>[...WD].filter(([name])=>text.includes(name)).map(([,n])=>n);
export async function handleConversation({userId,displayName="שחקן/ית",text="",actionId,store,now=new Date(),availabilityFn=findAvailability}){
 const input=(actionId||text).trim(),state=await store.get(`state/${userId}`)||{}; const set=async s=>store.set(`state/${userId}`,s);
 const withMyRequests=async r=>(await userActiveRequests(store,userId,now)).length?{...r,buttons:[...(r.buttons||[]).slice(0,2),MY_REQ]}:r;
 const ownReq=async rid=>{const r=await store.get(`request/${rid}`);return r&&r.active&&r.userId===userId?r:null;};
 const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jerusalem"}).format(now);
 const seenKey=`seen/${userId}`,seen=await store.get(seenKey);if(!seen)await store.set(seenKey,{at:now.toISOString()});
 const profileKey=`profile/${userId}`,profile=await store.get(profileKey)||{userId},name=profile.name||null;
 if(name)displayName=name;
 const saveName=async n=>{const p=await store.get(profileKey)||{userId};p.name=n;await store.set(profileKey,p);for(const r of await store.list("request/"))if(r.value.userId===userId&&r.value.active){await store.set(`request/${r.value.id}`,{...r.value,displayName:n});}};
 if(state.step==="name_confirm"&&(input==="name_yes"||input==="name_no")){await set({});if(input==="name_no")return btn(`בסדר, השם נשאר ${state.oldName}.`,[{id:"menu",title:"לתפריט"}]);await saveName(state.newName);return btn(`השם עודכן ל-${state.newName}.`,[{id:"menu",title:"לתפריט"}]);}
 const askConfirm=async n=>{await set({step:"name_confirm",oldName:name,newName:n});return btn(`לאשר שינוי שם מ-${name} ל-${n}?`,[{id:"name_yes",title:"כן, לשנות"},{id:"name_no",title:"לא"}]);};
 if(state.step==="name"&&text&&!actionId&&!/^(היי|הי|שלום|תפריט|menu|start)$/i.test(text.trim())){const n=cleanName(text);if(!n)return{text:"לא הצלחתי לקלוט שם. מה השם שלך? (למשל: יוסי)"};if(state.change&&name){if(n===name){await set({});return{text:`השם כבר ${name}.`};}return askConfirm(n);}await saveName(n);await set(state.resume||{});const pending=state.pending;if(pending)return handleConversation({userId,displayName:n,actionId:pending,store,now,availabilityFn});return btn(`נעים להכיר, ${n}!`,[{id:"availability",title:"מגרש פנוי"},{id:"players",title:"מציאת שחקנים"}]);}
 if(text&&!actionId){const c=nameChangeIntent(text);if(c){if(c.name&&name){if(c.name===name)return{text:`השם כבר ${name}.`};return askConfirm(c.name);}if(c.name&&!name){await saveName(c.name);await set({});return btn(`נעים להכיר, ${c.name}!`,[{id:"availability",title:"מגרש פנוי"},{id:"players",title:"מציאת שחקנים"}]);}await set({step:"name",change:true});return{text:name?`השם הנוכחי: ${name}. מה השם שלך?`:"מה השם שלך?"};}}
 // Tom 23.9: flow questions first; the name is asked only where it is needed (publishing a request / connecting).
 if(!name&&input.startsWith("connect:")){await set({step:"name",pending:input});return{text:NAME_ASK};}
 if(/^(היי|הי|שלום|תפריט|menu|start)$/i.test(input)||input==="menu"){if(state.step)await set({});return withMyRequests(welcome(name));}
 // Tom 23.9 hour rule: 8, 9, 10 with no morning/evening cue -> ask, never guess.
 if(state.step==="ampm"&&(input==="ampm:am"||input==="ampm:pm")){await set(state.apResume||{});return handleConversation({userId,displayName,text:`${state.apText} ${input==="ampm:am"?"בבוקר":"בערב"}`,store,now,availabilityFn});}
 // Request management (Tom 23.9 13:18): view / edit one field / delete. Editing never notifies an already-connected player.
 if(input.startsWith("req:")){const r=await ownReq(input.slice(4));if(!r)return btn("הבקשה כבר לא פעילה.",[MY_REQ,MENU]);return btn(`*${reqTitle(r)}*\n${reqDesc(r)}`,[{id:`edit:${r.id}`,title:"עריכה"},{id:`del:${r.id}`,title:"מחיקה"},{id:"my_requests",title:"חזרה"}]);}
 if(input.startsWith("del:")){const r=await ownReq(input.slice(4));if(!r)return btn("הבקשה כבר לא פעילה.",[MY_REQ,MENU]);return btn(`למחוק את הבקשה ל${reqTitle(r)}?`,[{id:`delok:${r.id}`,title:"כן, למחוק"},{id:"my_requests",title:"לא"}]);}
 if(input.startsWith("delok:")){const r=await ownReq(input.slice(6));if(!r)return btn("הבקשה כבר לא פעילה.",[MY_REQ,MENU]);await store.set(`request/${r.id}`,{...r,active:false,deletedAt:now.toISOString()});await set({});return btn("מחקתי את הבקשה.",[MY_REQ,MENU]);}
 if(input.startsWith("edit:")){const r=await ownReq(input.slice(5));if(!r)return btn("הבקשה כבר לא פעילה.",[MY_REQ,MENU]);const f=[["when","יום ושעה"],["level","רמה"],["duration","משך"],["party","מספר שחקנים"],["court","מגרש"]].concat(r.hasCourt?[]:[["flex","גמישות"]]);return list(`מה לשנות ב${reqTitle(r)}?`,f.map(([k,t])=>({id:`ef:${r.id}:${k}`,title:t})).concat({id:"my_requests",title:"חזרה"}));}
 if(input.startsWith("ef:")){const [,rid,field]=input.split(":"),r=await ownReq(rid);if(!r)return btn("הבקשה כבר לא פעילה.",[MY_REQ,MENU]);await set({flow:"edit",step:`edit_${field}`,editId:r.id});
   if(field==="when")return{text:r.recurring?"באילו ימים ושעות אתם זמינים בדרך כלל? למשל: שני ורביעי אחרי 20:00":"מתי תרצו לשחק? אפשר לכתוב למשל: מחר אחרי 19:00"};
   if(field==="level")return list("מה הרמה שלכם?",LEVEL_ROWS());if(field==="duration")return list("כמה זמן תרצו לשחק?",DURATION_ROWS());if(field==="party")return list("כמה שחקנים אתם?",PARTY_ROWS());
   if(field==="court")return btn("כבר יש לכם מגרש?",[{id:"court:yes",title:"כן"},{id:"court:no",title:"לא"}]);if(field==="flex")return list("עד כמה אתם גמישים בשעה?",FLEX_ROWS());await set({});return btn("לא הבנתי. אפשר לבחור מה לעשות:",[MY_REQ,MENU]);}
 if(state.flow==="edit"&&state.editId){const r=await ownReq(state.editId);if(!r){await set({});return btn("הבקשה כבר לא פעילה.",[MY_REQ,MENU]);}let patch=null;
   if(state.step==="edit_level"&&input.startsWith("level:"))patch={level:levelValue(input.slice(6))};
   else if(state.step==="edit_duration"&&input.startsWith("duration:")){const v=input.slice(9);patch={durations:v==="flex"?[60,90,120]:[Number(v)]};}
   else if(state.step==="edit_party"&&input.startsWith("party:"))patch={partySize:Number(input.slice(6))};
   else if(state.step==="edit_court"&&input.startsWith("court:")){const has=input.endsWith("yes");patch=has?{hasCourt:true,flexMinutes:0}:{hasCourt:false};}
   else if(state.step==="edit_flex"&&input.startsWith("flex:"))patch={flexMinutes:flexMinutesFor(input.slice(5))};
   else if(state.step==="edit_when"&&text&&!actionId){if(r.recurring&&!recurringDays(text).length)return{text:"בזמינות קבועה צריך לציין ימים בשבוע, למשל: שני ורביעי אחרי 20:00."};const p=await parseWhen(text,now);if(p.needsClarification==="unclear"&&!r.recurring)return{text:UNCLEAR_WHEN};if(p.ambiguousHour&&!r.recurring){await set({step:"ampm",apResume:state,apText:text});return btn(`התכוונת ל-${p.ambiguousHour} בבוקר או ל-${p.ambiguousHour} בערב?`,[{id:"ampm:am",title:`${p.ambiguousHour} בבוקר`},{id:"ampm:pm",title:`${p.ambiguousHour} בערב`}]);}patch={date:p.date,startMinute:p.startMinute??1140,endMinute:p.endMinute??1380,...(r.recurring?{weekdays:recurringDays(text)}:{})};}
   if(patch){const updated={...r,...patch,updatedAt:now.toISOString()};
     if(!updated.recurring&&!updated.hasCourt&&(patch.date||patch.durations||patch.hasCourt===false)){const a=await availabilityFn({date:updated.date,startMinute:updated.startMinute,endMinute:updated.endMinute,durationMinutes:updated.durations[0]},{today:today()});if(!a.slots?.length){await set({});return btn("לא מצאתי מגרש פנוי שמתאים לשינוי, אז הבקשה נשארה כמו שהייתה.",[MY_REQ,MENU]);}updated.courtSlot=a.slots[0];}
     await store.set(`request/${r.id}`,updated);await set({});const matches=await findMatches(store,updated,now);const resp=btn(`עדכנתי: ${reqTitle(updated)} · ${reqDesc(updated)}.${matchLines(updated,matches)}`,[MY_REQ,MENU]);if(matches.length)resp.notifications=matchNotifications(updated,matches);return resp;}
 }
 if(text&&!actionId&&(state.step?["avail_when","board_when","when"].includes(state.step):true)){const p=parseIntentLocal(text,now),h=p.ambiguousHour;if(h&&(state.step||p.dateExplicit)){await set({step:"ampm",apResume:state,apText:text});return btn(`התכוונת ל-${h} בבוקר או ל-${h} בערב?`,[{id:"ampm:am",title:`${h} בבוקר`},{id:"ampm:pm",title:`${h} בערב`}]);}}
 // Tom 23.9 10:36: "בשבוע הבא אחרי 18:00" got "לא הבנתי". "Next week" is a week, not a day: ask which day (dates listed), keep the time part, then continue the same step.
 if(text&&!actionId&&NEXT_WEEK.test(text)&&!recurringDays(text.replace(NEXT_WEEK,"")).length&&(!state.step||["avail_when","board_when","when"].includes(state.step))){const days=nextWeekDays(now);await set({step:"nw_day",nwResume:state,nwRest:text.replace(NEXT_WEEK,"").replace(/\s+/g," ").trim(),nwDays:days});return list("באיזה יום בשבוע הבא?",days.map((d,i)=>({id:`nw:${i}`,title:d.label})));}
 if(state.step==="nw_day"&&input.startsWith("nw:")){const d=state.nwDays?.[Number(input.slice(3))];if(d){await set(state.nwResume||{});return handleConversation({userId,displayName,text:`${d.ddmm} ${state.nwRest}`.trim(),store,now,availabilityFn});}}
 if(input==="availability"){await set({flow:"availability",step:"avail_when"});return list("מתי תרצו לשחק? בחרו מהרשימה או כתבו יום, שעה ומשך, למשל: מחר אחרי 19:00 ל90 דקות",WHEN_OPTIONS.map((x,i)=>({id:`when:${i}`,title:x})));}
 if(input.startsWith("when:")){await set({});return{mode:"availability",query:whenLabel(input.slice(5))};}
 if(state.step==="avail_when"&&text&&!actionId){await set({});return{mode:"availability",query:text};}
 if(input==="availability"||(!(!actionId&&["when","schedule","board_when"].includes(state.step))&&!/מי מחפש|שחקן פנוי|בקשות פתוחות/.test(input)&&/מגרש(?:ים)?(?:\s+פנוי)?|זמינות|איזה מגרשים|איפה מזמינים|מה פנוי|תבדוק|(?:היום|מחר|מחרתיים|ראשון|שני|שלישי|רביעי|חמישי|שישי|שבת|\d{1,2}[/.]\d{1,2}|\d{1,2}\s*לחודש).*(?:בוקר|צהריים|אחה"?צ|ערב|לילה|שעה|שעתיים|דקות|דק|\d{1,2}:\d{2}|אחרי\s*\d|לפני\s*\d|ב-?\d{1,2}\b)|^\s*\d{1,2}[/.]\d{1,2}\b/.test(input)))return{mode:"availability",query:text||input};
 if(input==="players"||/מציאת שחקנים/.test(input)){await set({flow:"players",step:"mode"});return btn(PLAYERS_MENU,[{id:"oneoff",title:"חסרים לי שחקנים"},{id:"board",title:"להצטרף למשחק חד-פעמי"},{id:"recurring",title:"משחק קבוע כל שבוע"}]);}
 if(input==="settings"||/הגדרות/.test(input))return btn("*ניהול הבקשות וההתראות*",[{id:"my_requests",title:"הבקשות שלי"},{id:"mute_week",title:"השתקה לשבוע"},{id:"mute_custom",title:"השתקה אחרת"}]);
 if(input==="mute_week"){const until=new Date(now);until.setDate(until.getDate()+7);await mute(store,userId,until.toISOString());return btn("ההתראות הושתקו לשבוע. אפשר לשנות זאת בכל רגע דרך תפריט ההגדרות.",[{id:"menu",title:"לתפריט"}]);}
 if(input==="mute_custom"){await set({...state,flow:"settings",step:"mute_days"});return list("לכמה זמן להשתיק התראות?",[1,3,7,14,30].map(d=>({id:`mute_${d}`,title:`${d} ימים`})));}
 if(/^mute_\d+$/.test(input)){const days=Number(input.slice(5)),until=new Date(now);until.setDate(until.getDate()+days);await mute(store,userId,until.toISOString());return{ text:`ההתראות הושתקו ל־${days} ימים.`};}
 if(input==="cancel_req"){await set({});return btn("בסדר, לא פתחתי בקשה.",[MENU]);}
 if(input==="my_requests"||/^הבקשות שלי$/.test(input)){await set({});const rows=await userActiveRequests(store,userId,now);if(!rows.length)return btn("אין לך כרגע בקשות פעילות.",[{id:"players",title:"בקשה חדשה"},MENU]);return{text:"*הבקשות שלי*",list:{button:"לבקשות",sections:[{title:"בקשות פעילות",rows:rows.map(r=>({id:`req:${r.id}`,title:reqTitle(r).slice(0,24),description:reqDesc(r).slice(0,72)})).concat(rows.length<MAX_ACTIVE_REQUESTS?[{id:"players",title:"➕ בקשה חדשה"}]:[],{id:"menu",title:"לתפריט"})}]}};}
 if(input==="board"){await set({flow:"board",step:"board_when"});return list("מתי תרצו לשחק? בחרו מהרשימה או כתבו יום ושעה, למשל: מחר אחרי 19:00",WHEN_OPTIONS.map((x,i)=>({id:`bwhen:${i}`,title:x})));}
 if(input.startsWith("bwhen:")||(state.step==="board_when"&&text&&!actionId)||/מי מחפש|שחקן פנוי|בקשות פתוחות/.test(input)){const q=input.startsWith("bwhen:")?whenLabel(input.slice(6)):text||input;if(state.step==="board_when")await set({});const p=await parseWhen(q,now);if(p.needsClarification==="unclear"){await set({step:"board_when"});return{text:UNCLEAR_WHEN};}const rows=await publicBoard(store,{date:p.date,startMinute:p.startMinute??0,endMinute:p.endMinute??1440,now});const head=`חיפשתי: ${whenEcho(p)}.\n\n`;if(!rows.length){// Tom 23.9: nothing open in the window -> open the request for the user, reusing level and duration from the last request.
   if((await userActiveRequests(store,userId,now)).length>=MAX_ACTIVE_REQUESTS)return btn(`אין כרגע משחקים פתוחים ב${whenEcho(p).replace(", "," ")}.\n\n${CAP_TEXT}`,[MY_REQ,MENU]);
   const last=await lastRequest(store,userId),draft={recurring:false,displayName,date:p.date,startMinute:p.startMinute??1140,endMinute:p.endMinute??1380},open=`אין כרגע משחקים פתוחים ב${whenEcho(p).replace(", "," ")}, אז אני פותח לך בקשה ואחפש לך שחקנים.`,cancel={id:"cancel_req",title:"ביטול"};
   if(last){draft.level=last.level;draft.durations=last.durations;await set({flow:"players",step:"party",draft});return list(`${open}\nלקחתי מהבקשה הקודמת: רמה ${last.level}, ${last.durations.length>1?"משך גמיש":`${last.durations[0]} דקות`}.\n\nכמה שחקנים אתם?`,PARTY_ROWS().concat(cancel));}
   await set({flow:"players",step:"level",draft});return list(`${open} מה הרמה שלך?`,LEVEL_ROWS().concat(cancel));}return{text:head+formatBoard(rows),list:{button:"לבקשות",sections:[{title:"בקשות פתוחות",rows:rows.slice(0,10).map(x=>({id:`connect:${x.id}`,title:`${x.displayName} · ${x.level}`,description:`${formatPhone(x.userId)} · ${clockLabel(x.startMinute)}–${clockLabel(x.endMinute)}`}))}]}};}

 if(input.startsWith("connect:")){const request=await store.get(`request/${input.slice(8)}`);if(!request||!request.active)return{text:"הבקשה כבר לא פעילה."};if(request.userId===userId)return{text:"זו הבקשה שלך."};const connectionId=id();await store.set(`connection/${connectionId}`,{id:connectionId,fromUserId:userId,fromDisplayName:displayName,toUserId:request.userId,requestId:request.id,status:"pending",createdAt:now.toISOString()});return{text:`שלחתי בקשת חיבור ל${request.displayName}. אעדכן כשיאשר/תאשר.`,notifications:[{to:request.userId,response:btn(`${displayName} רוצה להתחבר לבקשה שלך: ${request.date} · רמה ${request.level}. לחבר ביניכם?`,[{id:`accept:${connectionId}`,title:"כן, לחבר"},{id:`decline:${connectionId}`,title:"לא מתאים"},{id:"mute_week",title:"השתקה לשבוע"}])}]};}
 if(input.startsWith("accept:")||input.startsWith("decline:")){const connection=await store.get(`connection/${input.split(":")[1]}`);if(!connection||connection.toUserId!==userId)return{text:"הבקשה אינה זמינה."};connection.status=input.startsWith("accept:")?"accepted":"declined";await store.set(`connection/${connection.id}`,connection);if(connection.status==="declined")return{text:"סימנתי שלא מתאים.",notifications:[{to:connection.fromUserId,response:{text:"בקשת החיבור לא התאימה הפעם. אמשיך לחפש התאמות אחרות."}}]};return{text:`חיברתי ביניכם! אפשר ליצור קשר עם ${connection.fromDisplayName}: ${formatPhone(connection.fromUserId)}`,notifications:[{to:connection.fromUserId,response:{text:`${displayName} אישר/ה את החיבור. אפשר ליצור קשר: ${formatPhone(userId)}`}}]};}
 if(input==="oneoff"||input==="recurring"){if((await userActiveRequests(store,userId,now)).length>=MAX_ACTIVE_REQUESTS)return btn(CAP_TEXT,[MY_REQ,MENU]);await set({flow:"players",step:"level",draft:{recurring:input==="recurring",displayName}});return list("מה הרמה שלכם?",LEVELS.map((x,i)=>({id:`level:${i}`,title:levelTitle(x)})));}
 if(state.flow==="players"&&state.step==="level"&&input.startsWith("level:")){const draft={...state.draft,level:levelValue(input.slice(6))};if(!draft.recurring&&draft.date){await set({...state,step:"duration",draft});return list("כמה זמן תרצו לשחק?",DURATION_ROWS());}await set({...state,step:draft.recurring?"schedule":"when",draft});return draft.recurring?{text:"באילו ימים ושעות אתם זמינים בדרך כלל? למשל: שני ורביעי אחרי 20:00"}:{text:"מתי תרצו לשחק? אפשר לכתוב למשל: מחר אחרי 19:00"};}
 if(state.flow==="players"&&(state.step==="when"||state.step==="schedule")){
   if(state.step==="schedule"&&!recurringDays(text).length)return{text:"בזמינות קבועה צריך לציין ימים בשבוע, למשל: שני ורביעי אחרי 20:00. לחיפוש משחק ליום מסוים חזרו לתפריט ובחרו \"חסרים לי שחקנים\"."};
   const p=await parseWhen(text,now);if(p.needsClarification==="unclear"&&!state.draft.recurring)return{text:UNCLEAR_WHEN};if(p.ambiguousHour&&!state.draft.recurring){await set({step:"ampm",apResume:state,apText:text});return btn(`התכוונת ל-${p.ambiguousHour} בבוקר או ל-${p.ambiguousHour} בערב?`,[{id:"ampm:am",title:`${p.ambiguousHour} בבוקר`},{id:"ampm:pm",title:`${p.ambiguousHour} בערב`}]);}const draft={...state.draft,date:p.date,startMinute:p.startMinute??1140,endMinute:p.endMinute??1380,weekdays:state.draft.recurring?recurringDays(text):undefined};await set({...state,step:"duration",draft});return list(`${draft.recurring?"":`רשמתי: ${whenEcho(draft)}.\n\n`}כמה זמן תרצו לשחק?`,DURATIONS.map(d=>({id:`duration:${d}`,title:`${d} דקות`})).concat({id:"duration:flex",title:"גמיש"}));
 }
 if(state.flow==="players"&&state.step==="duration"&&input.startsWith("duration:")){const v=input.slice(9),draft={...state.draft,durations:v==="flex"?[60,90,120]:[Number(v)]};await set({...state,step:"party",draft});return list("כמה שחקנים אתם?",[{id:"party:1",title:"רק אני"},{id:"party:2",title:"אני ועוד אחד"},{id:"party:3",title:"שלושה, מחפשים רביעי"}]);}
 if(state.flow==="players"&&state.step==="party"&&input.startsWith("party:")){const draft={...state.draft,partySize:Number(input.slice(6))};await set({...state,step:"court",draft});return btn("כבר יש לכם מגרש?",[{id:"court:yes",title:"כן"},{id:"court:no",title:"לא"}]);}
 // Tom 23.9 13:14: "אם כבר יש לי מגרש אין טעם לשאול אם אנחנו גמישים בשעה" - with a court the time is fixed: skip the flex question (flex 0).
 if(state.flow==="players"&&state.step==="court"&&input.startsWith("court:")){const draft={...state.draft,hasCourt:input.endsWith("yes")};await set({...state,step:"flex",draft});if(draft.hasCourt)return handleConversation({userId,displayName,actionId:"flex:0",store,now,availabilityFn});return list("עד כמה אתם גמישים בשעה?",[{id:"flex:0",title:"שעה מדויקת"},{id:"flex:60",title:"שעה"},{id:"flex:any",title:"גמיש"}]);}
 // Tom 23.9 13:15: no mute offer on "הבקשה נשמרה" - mute is offered only inside notifications.
 if(state.flow==="players"&&state.step==="flex"&&input.startsWith("flex:")){if(!name){await set({step:"name",pending:input,resume:state});return{text:NAME_ASK};}const d=state.draft,request={...d,displayName,id:id(),userId,flexMinutes:flexMinutesFor(input.slice(5)),active:true,createdAt:now.toISOString()};if(!request.recurring&&!request.hasCourt){const availability=await availabilityFn({date:request.date,startMinute:request.startMinute,endMinute:request.endMinute,durationMinutes:request.durations[0]},{today:new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jerusalem"}).format(now)});if(!availability.slots?.length){await set({});return{text:"לא מצאתי מגרש פנוי שמתאים לחלון ולמשך שביקשתם. הבקשה לא פורסמה כדי שלא נחפש שחקנים למשחק שלא ניתן להזמין.",buttons:[{id:"players",title:"לנסות זמן אחר"},{id:"availability",title:"בדיקת זמינות"}]};}request.courtSlot=availability.slots[0];}await store.set(`request/${request.id}`,request);await set({});const matches=await findMatches(store,request,now);const response=btn(`הבקשה נשמרה ותופיע בלוח המשחקים.${matches.length?`\n\nמצאתי ${matches.length} התאמות אפשריות ושלחתי הצעה:\n${matches.slice(0,3).map(m=>`• ${m.displayName} · רמה ${m.level}${levelNote(request.level,m.level)}`).join("\n")}`:"\n\nאעדכן כשאמצא התאמה."}`,[MY_REQ,{id:"players",title:"בקשה נוספת"},MENU]);if(matches.length)response.notifications=matches.slice(0,3).map(m=>({to:m.userId,response:btn(`מצאתי התאמה אפשרית: ${request.displayName} · ${request.date} · רמה ${request.level}${levelNote(m.level,request.level)}. תרצו להתחבר?`,[{id:`connect:${request.id}`,title:"רוצה להתחבר"},{id:"mute_week",title:"השתקה לשבוע"},{id:"mute_custom",title:"השתקה אחרת"}])}));return response;}
 if(text.includes("?"))return btn("לא הצלחתי להבין את השאלה. אפשר לנסח אותה שוב בקצרה?",[{id:"menu",title:"לתפריט"}]);
 if(seen)return btn("לא הבנתי. אפשר לבחור מה לעשות:",[{id:"availability",title:"מגרש פנוי"},{id:"players",title:"מציאת שחקנים"}]);
 return withMyRequests(welcome(name));
}
