import crypto from "node:crypto";
import { parseIntentLocal } from "./intent.js";
import { findAvailability } from "./availability.js";
import { activeRequests, DURATIONS, findMatches, formatBoard, LEVELS, mute, publicBoard, welcome } from "./matching.js";
const withMenu=text=>`${text}\n\nכתבו *תפריט* בכל שלב כדי לראות את האפשרויות.`;
const btn=(text,buttons)=>({text,buttons:buttons.map(x=>typeof x==="string"?{id:x,title:x}:x)}), list=(text,items)=>({text,list:{button:"לבחירה",sections:[{title:"אפשרויות",rows:items}]}});
const id=()=>crypto.randomUUID();
const WD=new Map([["ראשון",0],["שני",1],["שלישי",2],["רביעי",3],["חמישי",4],["שישי",5],["שבת",6]]);
const recurringDays=text=>[...WD].filter(([name])=>text.includes(name)).map(([,n])=>n);
export async function handleConversation({userId,displayName="שחקן/ית",text="",actionId,store,now=new Date(),availabilityFn=findAvailability}){
 const input=(actionId||text).trim(),state=await store.get(`state/${userId}`)||{}; const set=async s=>store.set(`state/${userId}`,s);
 if(/^(היי|הי|שלום|תפריט|menu|start)$/i.test(input)||input==="menu")return welcome();
 if(input==="availability"||/מגרש(?:ים)?(?:\s+פנוי)?|זמינות|איזה מגרשים|איפה מזמינים|מה פנוי/.test(input))return{mode:"availability",query:text||input};
 if(input==="players"||/מציאת שחקנים/.test(input)){await set({flow:"players",step:"mode"});return btn("איך תרצו למצוא משחק?",[{id:"oneoff",title:"משחק נקודתי"},{id:"recurring",title:"זמינות קבועה"},{id:"board",title:"בקשות פתוחות"}]);}
 if(input==="settings"||/הגדרות|הבקשות שלי/.test(input))return btn("*ניהול הבקשות וההתראות*",[{id:"my_requests",title:"הבקשות שלי"},{id:"mute_week",title:"השתקה לשבוע"},{id:"mute_custom",title:"השתקה אחרת"}]);
 if(input==="mute_week"){const until=new Date(now);until.setDate(until.getDate()+7);await mute(store,userId,until.toISOString());return btn("ההתראות הושתקו לשבוע. אפשר לשנות זאת בכל רגע דרך תפריט ההגדרות.",[{id:"menu",title:"לתפריט"}]);}
 if(input==="mute_custom"){await set({...state,flow:"settings",step:"mute_days"});return list("לכמה זמן להשתיק התראות?",[1,3,7,14,30].map(d=>({id:`mute_${d}`,title:`${d} ימים`})));}
 if(/^mute_\d+$/.test(input)){const days=Number(input.slice(5)),until=new Date(now);until.setDate(until.getDate()+days);await mute(store,userId,until.toISOString());return{ text:`ההתראות הושתקו ל־${days} ימים.`};}
 if(input==="my_requests"){const rows=(await activeRequests(store,now)).filter(x=>x.userId===userId);return{text:rows.length?`*הבקשות שלי*\n${rows.map(x=>`• ${x.recurring?"קבועה":"חד־פעמית"} · ${x.date||x.weekdays.join(", ")} · רמה ${x.level}`).join("\n")}`:"אין לך כרגע בקשות פעילות."};}
 if(input==="board"||/מי מחפש|שחקן פנוי|בקשות פתוחות/.test(input)){const p=parseIntentLocal(text||input,now),rows=await publicBoard(store,{date:p.date,startMinute:p.startMinute??0,endMinute:p.endMinute??1440,now});if(!rows.length)return{text:withMenu(formatBoard(rows)),buttons:[{id:"menu",title:"לתפריט"}]};return{text:formatBoard(rows),list:{button:"לבקשות",sections:[{title:"בקשות פתוחות",rows:rows.slice(0,10).map(x=>({id:`connect:${x.id}`,title:`${x.displayName} · ${x.level}`,description:`${String(Math.floor(x.startMinute/60)).padStart(2,"0")}:${String(x.startMinute%60).padStart(2,"0")}–${String(Math.floor(x.endMinute/60)).padStart(2,"0")}:${String(x.endMinute%60).padStart(2,"0")}`}))}]}};}

 if(input.startsWith("connect:")){const request=await store.get(`request/${input.slice(8)}`);if(!request||!request.active)return{text:"הבקשה כבר לא פעילה."};if(request.userId===userId)return{text:"זו הבקשה שלך."};const connectionId=id();await store.set(`connection/${connectionId}`,{id:connectionId,fromUserId:userId,fromDisplayName:displayName,toUserId:request.userId,requestId:request.id,status:"pending",createdAt:now.toISOString()});return{text:`שלחתי בקשת חיבור ל${request.displayName}. פרטי הקשר יישארו חסויים עד לאישור.`,notifications:[{to:request.userId,response:btn(`${displayName} רוצה להתחבר לבקשה שלך: ${request.date} · רמה ${request.level}. לחבר ביניכם?`,[{id:`accept:${connectionId}`,title:"כן, לחבר"},{id:`decline:${connectionId}`,title:"לא מתאים"},{id:"mute_week",title:"השתקה לשבוע"}])}]};}
 if(input.startsWith("accept:")||input.startsWith("decline:")){const connection=await store.get(`connection/${input.split(":")[1]}`);if(!connection||connection.toUserId!==userId)return{text:"הבקשה אינה זמינה."};connection.status=input.startsWith("accept:")?"accepted":"declined";await store.set(`connection/${connection.id}`,connection);if(connection.status==="declined")return{text:"סימנתי שלא מתאים. פרטי קשר לא נחשפו.",notifications:[{to:connection.fromUserId,response:{text:"בקשת החיבור לא התאימה הפעם. אמשיך לחפש התאמות אחרות."}}]};return{text:`חיברתי ביניכם בתוך הבוט. אפשר לתאם כאן דרך בקשות הדדיות; מספרי הטלפון נשארים חסויים.`,notifications:[{to:connection.fromUserId,response:{text:`${displayName} אישר/ה את החיבור. אפשר להמשיך בתיאום דרך הבוט; מספרי הטלפון נשארים חסויים.`}}]};}
 if(input==="oneoff"||input==="recurring"){await set({flow:"players",step:"level",draft:{recurring:input==="recurring",displayName}});return list("מה הרמה שלכם?",LEVELS.map(x=>({id:`level:${x}`,title:x})));}
 if(state.flow==="players"&&state.step==="level"&&input.startsWith("level:")){const draft={...state.draft,level:input.slice(6)};await set({...state,step:draft.recurring?"schedule":"when",draft});return draft.recurring?{text:"באילו ימים ושעות אתם זמינים בדרך כלל? למשל: שני ורביעי אחרי 20:00"}:{text:"מתי תרצו לשחק? אפשר לכתוב למשל: מחר אחרי 19:00"};}
 if(state.flow==="players"&&(state.step==="when"||state.step==="schedule")){
   const p=parseIntentLocal(text,now),draft={...state.draft,date:p.date,startMinute:p.startMinute??1020,endMinute:p.endMinute??1380,weekdays:state.draft.recurring?recurringDays(text):undefined};await set({...state,step:"duration",draft});return list("כמה זמן תרצו לשחק?",DURATIONS.map(d=>({id:`duration:${d}`,title:`${d} דקות`})).concat({id:"duration:flex",title:"גמיש"}));
 }
 if(state.flow==="players"&&state.step==="duration"&&input.startsWith("duration:")){const v=input.slice(9),draft={...state.draft,durations:v==="flex"?[60,90,120]:[Number(v)]};await set({...state,step:"party",draft});return list("כמה שחקנים כבר יש בבקשה?",[1,2,3].map(n=>({id:`party:${n}`,title:`${n}`})));}
 if(state.flow==="players"&&state.step==="party"&&input.startsWith("party:")){const draft={...state.draft,partySize:Number(input.slice(6))};await set({...state,step:"court",draft});return btn("כבר יש לכם מגרש?",[{id:"court:yes",title:"כן"},{id:"court:no",title:"לא"}]);}
 if(state.flow==="players"&&state.step==="court"&&input.startsWith("court:")){const draft={...state.draft,hasCourt:input.endsWith("yes")};await set({...state,step:"flex",draft});return list("עד כמה אתם גמישים בשעה?",[{id:"flex:0",title:"שעה מדויקת"},{id:"flex:30",title:"חצי שעה"},{id:"flex:60",title:"שעה"}]);}
 if(state.flow==="players"&&state.step==="flex"&&input.startsWith("flex:")){const d=state.draft,request={...d,id:id(),userId,flexMinutes:Number(input.slice(5)),active:true,createdAt:now.toISOString()};if(!request.recurring&&!request.hasCourt){const availability=await availabilityFn({date:request.date,startMinute:request.startMinute,endMinute:request.endMinute,durationMinutes:request.durations[0]},{today:new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jerusalem"}).format(now)});if(!availability.slots?.length){await set({});return{text:"לא מצאתי מגרש פנוי שמתאים לחלון ולמשך שביקשתם. הבקשה לא פורסמה כדי שלא נחפש שחקנים למשחק שלא ניתן להזמין.",buttons:[{id:"players",title:"לנסות זמן אחר"},{id:"availability",title:"בדיקת זמינות"}]};}request.courtSlot=availability.slots[0];}await store.set(`request/${request.id}`,request);await set({});const matches=await findMatches(store,request,now);const response=btn(`הבקשה נשמרה ותופיע בלוח הציבורי בשם ${request.displayName}. מספרי טלפון לא יוצגו.${matches.length?`\n\nמצאתי ${matches.length} התאמות אפשריות ושלחתי הצעה.`:"\n\nאעדכן כשאמצא התאמה."}`,[{id:"mute_week",title:"השתקה לשבוע"},{id:"mute_custom",title:"השתקה אחרת"}]);if(matches.length)response.notifications=matches.slice(0,3).map(m=>({to:m.userId,response:btn(`מצאתי התאמה אפשרית: ${request.displayName} · ${request.date} · רמה ${request.level}. תרצו להתחבר?`,[{id:`connect:${request.id}`,title:"רוצה להתחבר"},{id:"mute_week",title:"השתקה לשבוע"},{id:"mute_custom",title:"השתקה אחרת"}])}));return response;}
 if(text.includes("?"))return btn(withMenu("לא הצלחתי להבין את השאלה. אפשר לנסח אותה שוב בקצרה?"),[{id:"menu",title:"לתפריט"}]);
 return welcome();
}
