import crypto from "node:crypto";
import { parseIntentLocal } from "./intent.js";
import { findAvailability } from "./availability.js";
import { activeRequests, DURATIONS, findMatches, formatBoard, LEVELS, levelTitle, levelNote, flexMinutesFor, mute, publicBoard, welcome, formatPhone } from "./matching.js";
const withMenu=text=>`${text}\n\nכתבו *תפריט* בכל שלב כדי לראות את האפשרויות.`;
const btn=(text,buttons)=>({text,buttons:buttons.map(x=>typeof x==="string"?{id:x,title:x}:x)}), list=(text,items)=>({text,list:{button:"לבחירה",sections:[{title:"אפשרויות",rows:items}]}});
const id=()=>crypto.randomUUID();
const NAME_ASK="מה השם שלך? כך תופיעו בלוח המשחקים.";
export function cleanName(raw){let t=String(raw||"").replace(/^(אני\s+)?(קוראים לי|שמי|השם שלי(?:\s+הוא)?|תקרא(?:ו)? לי|תקראי לי)\s*/,"").replace(/[.!?,"'״׳:;()]/g," ").replace(/\s+/g," ").trim();if(!t||t.length>30||/\d|@/.test(t)||t.split(" ").length>3)return null;if(/^(לא|כן|תפריט|שלום|היי|הי|אוקי|בסדר|menu|hi)$/i.test(t))return null;if(t.split(" ").some(w=>/^(מה|איך|מתי|כמה|איפה|למה|מי|יש|אין|רוצה|רוצים|מגרש|מגרשים|משחק|שחקן|שחקנים|פנוי|מחר|היום|בערב|בבוקר|תודה|אפשר|צריך|בוקר|ערב|טוב|קורה|שלום)$/.test(w)))return null;return t;}
export function nameChangeIntent(text){const t=String(text||"").trim();if(!t)return null;let m=t.match(/^(?:אני\s+)?(?:קוראים לי|שמי)\s+(.+)$/);if(m)return{name:cleanName(m[1])};if(/השם שלי(?:\s+הוא)?\s+לא(?:\s|$)/.test(t))return{name:null};m=t.match(/(?:לשנות|לעדכן|להחליף|תשנה|תעדכן|תחליף|שנה|תחליפו|תשנו)\s+(?:לי\s+)?(?:את\s+)?(?:ה)?שם(?:\s+שלי)?(?:\s+ל[-־]?\s*(\S.*))?$/);if(m)return{name:m[1]?cleanName(m[1]):null};m=t.match(/^(?:אבל\s+)?השם שלי(?:\s+הוא)?\s+(?!לא(?:\s|$))(.+)$/);if(m)return{name:cleanName(m[1])};if(/השם שלי(?:\s+הוא)?\s+לא(?:\s|$)/.test(t)||/(?:לשנות|לעדכן|שינוי|עדכון|להחליף)\s+(?:את\s+)?(?:ה)?שם/.test(t)||/השם\s+(?:שלי\s+)?לא\s+נכון/.test(t))return{name:null};return null;}
const WD=new Map([["ראשון",0],["שני",1],["שלישי",2],["רביעי",3],["חמישי",4],["שישי",5],["שבת",6]]);
const recurringDays=text=>[...WD].filter(([name])=>text.includes(name)).map(([,n])=>n);
export async function handleConversation({userId,displayName="שחקן/ית",text="",actionId,store,now=new Date(),availabilityFn=findAvailability}){
 const input=(actionId||text).trim(),state=await store.get(`state/${userId}`)||{}; const set=async s=>store.set(`state/${userId}`,s);
 const seenKey=`seen/${userId}`,seen=await store.get(seenKey);if(!seen)await store.set(seenKey,{at:now.toISOString()});
 const profileKey=`profile/${userId}`,profile=await store.get(profileKey)||{userId},name=profile.name||null;
 if(name)displayName=name;
 const saveName=async n=>{const p=await store.get(profileKey)||{userId};p.name=n;await store.set(profileKey,p);for(const r of await store.list("request/"))if(r.value.userId===userId&&r.value.active){await store.set(`request/${r.value.id}`,{...r.value,displayName:n});}};
 if(state.step==="name_confirm"&&(input==="name_yes"||input==="name_no")){await set({});if(input==="name_no")return btn(`בסדר, השם נשאר ${state.oldName}.`,[{id:"menu",title:"לתפריט"}]);await saveName(state.newName);return btn(`השם עודכן ל-${state.newName}.`,[{id:"menu",title:"לתפריט"}]);}
 const askConfirm=async n=>{await set({step:"name_confirm",oldName:name,newName:n});return btn(`לאשר שינוי שם מ-${name} ל-${n}?`,[{id:"name_yes",title:"כן, לשנות"},{id:"name_no",title:"לא"}]);};
 if(state.step==="name"&&text&&!actionId&&!/^(היי|הי|שלום|תפריט|menu|start)$/i.test(text.trim())){const n=cleanName(text);if(!n)return{text:"לא הצלחתי לקלוט שם. מה השם שלך? (למשל: יוסי)"};if(state.change&&name){if(n===name){await set({});return{text:`השם כבר ${name}.`};}return askConfirm(n);}await saveName(n);await set({});const pending=state.pending;if(pending)return handleConversation({userId,displayName:n,actionId:pending,store,now,availabilityFn});return btn(`נעים להכיר, ${n}!`,[{id:"availability",title:"מגרש פנוי"},{id:"players",title:"מציאת שחקנים"}]);}
 if(text&&!actionId){const c=nameChangeIntent(text);if(c){if(c.name&&name){if(c.name===name)return{text:`השם כבר ${name}.`};return askConfirm(c.name);}if(c.name&&!name){await saveName(c.name);await set({});return btn(`נעים להכיר, ${c.name}!`,[{id:"availability",title:"מגרש פנוי"},{id:"players",title:"מציאת שחקנים"}]);}await set({step:"name",change:true});return{text:name?`השם הנוכחי: ${name}. מה השם שלך?`:"מה השם שלך?"};}}
 if(!name&&(input==="oneoff"||input==="recurring"||input.startsWith("connect:"))){await set({step:"name",pending:input});return{text:NAME_ASK};}
 if(/^(היי|הי|שלום|תפריט|menu|start)$/i.test(input)||input==="menu"){if(state.step)await set({});return welcome(name);}
 if(input==="availability"){await set({flow:"availability",step:"avail_when"});return list("מתי תרצו לשחק? בחרו מהרשימה או כתבו יום, שעה ומשך, למשל: מחר אחרי 19:00 ל90 דקות",["היום בערב","מחר בבוקר","מחר בערב","שישי בבוקר","שבת בבוקר"].map(x=>({id:`when:${x}`,title:x})));}
 if(input.startsWith("when:")){await set({});return{mode:"availability",query:input.slice(5)};}
 if(state.step==="avail_when"&&text&&!actionId){await set({});return{mode:"availability",query:text};}
 if(input==="availability"||(!(!actionId&&["when","schedule"].includes(state.step))&&!/מי מחפש|שחקן פנוי|בקשות פתוחות/.test(input)&&/מגרש(?:ים)?(?:\s+פנוי)?|זמינות|איזה מגרשים|איפה מזמינים|מה פנוי|תבדוק|(?:היום|מחר|מחרתיים|ראשון|שני|שלישי|רביעי|חמישי|שישי|שבת|\d{1,2}[/.]\d{1,2}|\d{1,2}\s*לחודש).*(?:בוקר|צהריים|אחה"?צ|ערב|לילה|שעה|שעתיים|דקות|דק|\d{1,2}:\d{2}|אחרי\s*\d|לפני\s*\d|ב-?\d{1,2}\b)|^\s*\d{1,2}[/.]\d{1,2}\b/.test(input)))return{mode:"availability",query:text||input};
 if(input==="players"||/מציאת שחקנים/.test(input)){await set({flow:"players",step:"mode"});return btn("רוצים להצטרף למשחק קיים, או לחפש שחקנים שישלימו לכם רביעייה? אפשר גם לרשום את הזמינות השבועית והמערכת תנסה לשדך שחקנים",[{id:"oneoff",title:"חסרים לי שחקנים"},{id:"board",title:"להצטרף למשחק חד-פעמי"},{id:"recurring",title:"משחק קבוע כל שבוע"}]);}
 if(input==="settings"||/הגדרות|הבקשות שלי/.test(input))return btn("*ניהול הבקשות וההתראות*",[{id:"my_requests",title:"הבקשות שלי"},{id:"mute_week",title:"השתקה לשבוע"},{id:"mute_custom",title:"השתקה אחרת"}]);
 if(input==="mute_week"){const until=new Date(now);until.setDate(until.getDate()+7);await mute(store,userId,until.toISOString());return btn("ההתראות הושתקו לשבוע. אפשר לשנות זאת בכל רגע דרך תפריט ההגדרות.",[{id:"menu",title:"לתפריט"}]);}
 if(input==="mute_custom"){await set({...state,flow:"settings",step:"mute_days"});return list("לכמה זמן להשתיק התראות?",[1,3,7,14,30].map(d=>({id:`mute_${d}`,title:`${d} ימים`})));}
 if(/^mute_\d+$/.test(input)){const days=Number(input.slice(5)),until=new Date(now);until.setDate(until.getDate()+days);await mute(store,userId,until.toISOString());return{ text:`ההתראות הושתקו ל־${days} ימים.`};}
 if(input==="my_requests"){const rows=(await activeRequests(store,now)).filter(x=>x.userId===userId);return{text:rows.length?`*הבקשות שלי*\n${rows.map(x=>`• ${x.recurring?"קבועה":"חד־פעמית"} · ${x.date||x.weekdays.join(", ")} · רמה ${x.level}`).join("\n")}`:"אין לך כרגע בקשות פעילות."};}
 if(input==="board"||/מי מחפש|שחקן פנוי|בקשות פתוחות/.test(input)){const p=parseIntentLocal(text||input,now),rows=await publicBoard(store,{date:p.date,startMinute:p.startMinute??0,endMinute:p.endMinute??1440,now});if(!rows.length)return{text:withMenu(formatBoard(rows)),buttons:[{id:"menu",title:"לתפריט"}]};return{text:formatBoard(rows),list:{button:"לבקשות",sections:[{title:"בקשות פתוחות",rows:rows.slice(0,10).map(x=>({id:`connect:${x.id}`,title:`${x.displayName} · ${x.level}`,description:`${formatPhone(x.userId)} · ${String(Math.floor(x.startMinute/60)).padStart(2,"0")}:${String(x.startMinute%60).padStart(2,"0")}–${String(Math.floor(x.endMinute/60)).padStart(2,"0")}:${String(x.endMinute%60).padStart(2,"0")}`}))}]}};}

 if(input.startsWith("connect:")){const request=await store.get(`request/${input.slice(8)}`);if(!request||!request.active)return{text:"הבקשה כבר לא פעילה."};if(request.userId===userId)return{text:"זו הבקשה שלך."};const connectionId=id();await store.set(`connection/${connectionId}`,{id:connectionId,fromUserId:userId,fromDisplayName:displayName,toUserId:request.userId,requestId:request.id,status:"pending",createdAt:now.toISOString()});return{text:`שלחתי בקשת חיבור ל${request.displayName}. אעדכן כשיאשר/תאשר.`,notifications:[{to:request.userId,response:btn(`${displayName} רוצה להתחבר לבקשה שלך: ${request.date} · רמה ${request.level}. לחבר ביניכם?`,[{id:`accept:${connectionId}`,title:"כן, לחבר"},{id:`decline:${connectionId}`,title:"לא מתאים"},{id:"mute_week",title:"השתקה לשבוע"}])}]};}
 if(input.startsWith("accept:")||input.startsWith("decline:")){const connection=await store.get(`connection/${input.split(":")[1]}`);if(!connection||connection.toUserId!==userId)return{text:"הבקשה אינה זמינה."};connection.status=input.startsWith("accept:")?"accepted":"declined";await store.set(`connection/${connection.id}`,connection);if(connection.status==="declined")return{text:"סימנתי שלא מתאים.",notifications:[{to:connection.fromUserId,response:{text:"בקשת החיבור לא התאימה הפעם. אמשיך לחפש התאמות אחרות."}}]};return{text:`חיברתי ביניכם! אפשר ליצור קשר עם ${connection.fromDisplayName}: ${formatPhone(connection.fromUserId)}`,notifications:[{to:connection.fromUserId,response:{text:`${displayName} אישר/ה את החיבור. אפשר ליצור קשר: ${formatPhone(userId)}`}}]};}
 if(input==="oneoff"||input==="recurring"){await set({flow:"players",step:"level",draft:{recurring:input==="recurring",displayName}});return list("מה הרמה שלכם?",LEVELS.map(x=>({id:`level:${x}`,title:levelTitle(x)})));}
 if(state.flow==="players"&&state.step==="level"&&input.startsWith("level:")){const draft={...state.draft,level:input.slice(6)};await set({...state,step:draft.recurring?"schedule":"when",draft});return draft.recurring?{text:"באילו ימים ושעות אתם זמינים בדרך כלל? למשל: שני ורביעי אחרי 20:00"}:{text:"מתי תרצו לשחק? אפשר לכתוב למשל: מחר אחרי 19:00"};}
 if(state.flow==="players"&&(state.step==="when"||state.step==="schedule")){
   if(state.step==="schedule"&&!recurringDays(text).length)return{text:"בזמינות קבועה צריך לציין ימים בשבוע, למשל: שני ורביעי אחרי 20:00. לחיפוש משחק ליום מסוים חזרו לתפריט ובחרו \"חסרים לי שחקנים\"."};
   const p=parseIntentLocal(text,now),draft={...state.draft,date:p.date,startMinute:p.startMinute??1020,endMinute:p.endMinute??1380,weekdays:state.draft.recurring?recurringDays(text):undefined};await set({...state,step:"duration",draft});return list("כמה זמן תרצו לשחק?",DURATIONS.map(d=>({id:`duration:${d}`,title:`${d} דקות`})).concat({id:"duration:flex",title:"גמיש"}));
 }
 if(state.flow==="players"&&state.step==="duration"&&input.startsWith("duration:")){const v=input.slice(9),draft={...state.draft,durations:v==="flex"?[60,90,120]:[Number(v)]};await set({...state,step:"party",draft});return list("כמה שחקנים אתם?",[{id:"party:1",title:"רק אני"},{id:"party:2",title:"אני ועוד אחד"},{id:"party:3",title:"שלושה, מחפשים רביעי"}]);}
 if(state.flow==="players"&&state.step==="party"&&input.startsWith("party:")){const draft={...state.draft,partySize:Number(input.slice(6))};await set({...state,step:"court",draft});return btn("כבר יש לכם מגרש?",[{id:"court:yes",title:"כן"},{id:"court:no",title:"לא"}]);}
 if(state.flow==="players"&&state.step==="court"&&input.startsWith("court:")){const draft={...state.draft,hasCourt:input.endsWith("yes")};await set({...state,step:"flex",draft});return list("עד כמה אתם גמישים בשעה?",[{id:"flex:0",title:"שעה מדויקת"},{id:"flex:60",title:"שעה"},{id:"flex:any",title:"גמיש"}]);}
 if(state.flow==="players"&&state.step==="flex"&&input.startsWith("flex:")){const d=state.draft,request={...d,id:id(),userId,flexMinutes:flexMinutesFor(input.slice(5)),active:true,createdAt:now.toISOString()};if(!request.recurring&&!request.hasCourt){const availability=await availabilityFn({date:request.date,startMinute:request.startMinute,endMinute:request.endMinute,durationMinutes:request.durations[0]},{today:new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jerusalem"}).format(now)});if(!availability.slots?.length){await set({});return{text:"לא מצאתי מגרש פנוי שמתאים לחלון ולמשך שביקשתם. הבקשה לא פורסמה כדי שלא נחפש שחקנים למשחק שלא ניתן להזמין.",buttons:[{id:"players",title:"לנסות זמן אחר"},{id:"availability",title:"בדיקת זמינות"}]};}request.courtSlot=availability.slots[0];}await store.set(`request/${request.id}`,request);await set({});const matches=await findMatches(store,request,now);const response=btn(`הבקשה נשמרה ותופיע בלוח המשחקים.${matches.length?`\n\nמצאתי ${matches.length} התאמות אפשריות ושלחתי הצעה:\n${matches.slice(0,3).map(m=>`• ${m.displayName} · רמה ${m.level}${levelNote(request.level,m.level)}`).join("\n")}`:"\n\nאעדכן כשאמצא התאמה."}`,[{id:"mute_week",title:"השתקה לשבוע"},{id:"mute_custom",title:"השתקה אחרת"}]);if(matches.length)response.notifications=matches.slice(0,3).map(m=>({to:m.userId,response:btn(`מצאתי התאמה אפשרית: ${request.displayName} · ${request.date} · רמה ${request.level}${levelNote(m.level,request.level)}. תרצו להתחבר?`,[{id:`connect:${request.id}`,title:"רוצה להתחבר"},{id:"mute_week",title:"השתקה לשבוע"},{id:"mute_custom",title:"השתקה אחרת"}])}));return response;}
 if(text.includes("?"))return btn(withMenu("לא הצלחתי להבין את השאלה. אפשר לנסח אותה שוב בקצרה?"),[{id:"menu",title:"לתפריט"}]);
 if(seen)return btn("לא הבנתי. אפשר לבחור מה לעשות:",[{id:"availability",title:"מגרש פנוי"},{id:"players",title:"מציאת שחקנים"}]);
 return welcome(name);
}
