import { bookingUrl, slotFromActionId, findAvailability } from "./availability.js";
import { staticData } from "./matchpointer.js";
import {GT_VENUE,assertVenueResponse} from "./venues.js";
// Critique 23.9 item 12: the booking card names the court, the full time range and the price, and says booking ends on the site.
const endOf=(start,dur)=>{const [h,m]=start.split(":").map(Number),t=h*60+m+dur;return`${String(Math.floor(t/60)%24).padStart(2,"0")}:${String(t%60).padStart(2,"0")}`;};
async function courtName(id,venue=GT_VENUE){try{return(await staticData(fetch,Date.now(),venue)).courts.find(c=>c.id===id)?.name||"";}catch{return"";}}
export const bookingCard=(slot,court)=>`${court?`מגרש ${court} · `:""}${slot.start}–${endOf(slot.start,slot.durationMinutes)}${slot.price!=null?` · ₪${slot.price}`:""}\nההזמנה מסתיימת באתר.`;
import {answerResponse}from"./agent.js";import{handleConversation}from"./conversation.js";import{recordInbound,takePending,hasPending}from"./notify.js";
export const withMenu=r=>{if(!r?.text)return r;if(r.choices?.length)return{text:r.text,list:{button:"לבחירת שעה",sections:[{title:"שעות פנויות",rows:[...r.choices.slice(0,9).map(x=>({id:x.id,title:x.title,description:x.description})),{id:"menu",title:"לתפריט"}]}]}};if(r.text.includes("מה תרצו לעשות?")&&r.buttons?.some(x=>x.id==="availability")&&r.buttons?.some(x=>x.id==="players"))return r;let out={...r};/* Tom 23.9: no "כתבו תפריט" line; every message carries a menu button or menu row instead. */if(out.list){const hasMenu=out.list.sections.some(s=>s.rows.some(x=>x.id==="menu")),sections=out.list.sections.map((s,i)=>i||hasMenu?{...s}:{...s,rows:[...s.rows,{id:"menu",title:"לתפריט"}]});out={...out,list:{...out.list,sections}};}else if(out.buttons&&out.buttons.length<3&&!out.buttons.some(x=>x.id==="menu"))out={...out,buttons:[...out.buttons,{id:"menu",title:"לתפריט"}]};else if(!out.buttons)out={...out,buttons:[{id:"menu",title:"לתפריט"}]};return out;};
export async function routeIncoming({userId,displayName,text="",actionId,store,now=new Date(),availabilityFn,venue=GT_VENUE}){await recordInbound(store,userId,now);const yes=actionId==="pending_yes"||(!actionId&&/^(כן|כן, שלחו פרטים|כן שלחו פרטים|שלחו פרטים)$/.test(text.trim())&&await hasPending(store,userId));if(yes){const items=await takePending(store,userId);if(!items.length)return withMenu({text:"אין כרגע התאמות שממתינות לך."});const[first,...rest]=items;return withMenu({...first.response,notifications:[...(first.response.notifications||[]),...rest.map(i=>({to:userId,response:i.response}))]});}if(actionId==="pending_no"){await takePending(store,userId);return withMenu({text:"בסדר, לא אשלח את הפרטים."});}if(actionId?.startsWith("bk:")){const d=slotFromActionId(actionId),url=d&&bookingUrl(d.date,d.slot,{user:userId,venue});if(url)return{text:bookingCard(d.slot,await courtName(d.slot.courtId,venue)),ctaUrl:{displayText:`להזמנה ${d.slot.start}`.slice(0,20),url}};}if(actionId?.startsWith("book:")){const tracked=new URL(Buffer.from(actionId.slice(5),"base64url").toString("utf8"));assertVenueResponse(venue,{ctaUrl:{url:tracked.toString()}});if(/^\d{6,15}$/.test(String(userId)))tracked.searchParams.set("user",String(userId));const url=tracked.toString(),time=tracked.searchParams.get("time");return{text:`${time}${tracked.searchParams.get("duration")?`–${endOf(time,Number(tracked.searchParams.get("duration")))}`:""}${tracked.searchParams.get("price")?` · ₪${tracked.searchParams.get("price")}`:""}\nההזמנה מסתיימת באתר.`,ctaUrl:{displayText:`להזמנה ${time}`.slice(0,20),url}};}const venueAvailability=availabilityFn||((intent,options={})=>findAvailability(intent,{...options,venue}));const result=await handleConversation({userId,displayName,text,actionId,store,now,availabilityFn:venueAvailability});if(result.mode==="availability")return withMenu(await answerResponse(result.query,{now,availabilityFn:venueAvailability}));return withMenu(result);}
